// Generated by scripts/realign-cs-course.ts from the pre-realignment CS curriculum.
// Keep this explicit: aliases preserve URLs; the progress map is deliberately conservative.
export const csLegacyLessonAliases: Record<string, string[]> = {
  "1.1": [
    "computers-as-problem-solving-machines",
    "chapter-opening-so-what-exactly-is-a-computer",
    "chapter-roadmap-where-are-we-going"
  ],
  "1.2": [
    "algorithms"
  ],
  "1.3": [
    "computer-science-vs-programming"
  ],
  "1.4": [
    "computational-thinking"
  ],
  "1.7": [
    "practice",
    "chapter-summary",
    "closing-transition-but-how-does-a-computer-understand-information"
  ],
  "2.1": [
    "bits-and-bytes",
    "chapter-opening-everything-becomes-data",
    "chapter-roadmap"
  ],
  "2.2": [
    "binary-numbers"
  ],
  "2.3": [
    "hexadecimal"
  ],
  "2.4": [
    "floating-point-numbers"
  ],
  "2.5": [
    "representing-integers"
  ],
  "2.6": [
    "representing-text"
  ],
  "2.7": [
    "endianness"
  ],
  "3.1": [
    "boolean-logic",
    "chapter-opening-turning-0s-and-1s-into-decisions",
    "chapter-roadmap"
  ],
  "3.2": [
    "truth-tables"
  ],
  "3.3": [
    "and-or-not-xor"
  ],
  "3.4": [
    "logic-gates"
  ],
  "3.5": [
    "combinational-circuits"
  ],
  "3.6": [
    "sequential-circuits-state"
  ],
  "4.1": [
    "cpu",
    "chapter-opening-from-tiny-logic-gates-to-a-computer",
    "chapter-roadmap"
  ],
  "4.2": [
    "registers"
  ],
  "4.3": [
    "fetch-decode-execute"
  ],
  "4.4": [
    "main-memory"
  ],
  "4.5": [
    "cache"
  ],
  "4.6": [
    "persistent-storage"
  ],
  "4.7": [
    "input-output"
  ],
  "4.8": [
    "buses"
  ],
  "4.9": [
    "putting-everything-together"
  ],
  "5.1": [
    "source-code",
    "parsing",
    "complete-execution-journey",
    "chapter-opening-humans-and-cpus-speak-different-languages",
    "chapter-roadmap"
  ],
  "5.2": [
    "syntax-semantics",
    "syntax-trees"
  ],
  "5.3": [
    "compilers"
  ],
  "5.4": [
    "interpreters"
  ],
  "5.5": [
    "bytecode"
  ],
  "5.6": [
    "jit-compilation"
  ],
  "5.7": [
    "lexing"
  ],
  "5.8": [
    "tokens"
  ],
  "5.9": [
    "linking"
  ],
  "5.10": [
    "loading"
  ],
  "5.11": [
    "project-mini-expression-runtime",
    "chapter-summary",
    "unit-closing-transition"
  ],
  "6.1": [
    "files-folders",
    "editors-ides",
    "chapter-opening-before-we-code-we-need-somewhere-to-code",
    "chapter-roadmap"
  ],
  "6.2": [
    "source-code-files"
  ],
  "6.3": [
    "terminal"
  ],
  "6.4": [
    "running-your-first-program"
  ],
  "6.5": [
    "path"
  ],
  "6.6": [
    "environment-variables"
  ],
  "6.7": [
    "command-line-arguments"
  ],
  "6.8": [
    "lab-developer-workspace",
    "chapter-summary"
  ],
  "7.1": [
    "variables",
    "values",
    "floating-point",
    "chapter-opening-giving-programs-memory",
    "chapter-roadmap"
  ],
  "7.2": [
    "assignment"
  ],
  "7.3": [
    "integers"
  ],
  "7.4": [
    "booleans"
  ],
  "7.5": [
    "strings"
  ],
  "7.6": [
    "operators"
  ],
  "7.7": [
    "type-conversion"
  ],
  "7.8": [
    "mutability"
  ],
  "7.9": [
    "practice",
    "chapter-summary"
  ],
  "8.1": [
    "if-else",
    "if",
    "repetition",
    "chapter-opening-making-programs-think-in-paths",
    "chapter-roadmap"
  ],
  "8.2": [
    "nested-conditions"
  ],
  "8.3": [
    "for"
  ],
  "8.4": [
    "while"
  ],
  "8.5": [
    "break",
    "continue"
  ],
  "8.6": [
    "conditions"
  ],
  "8.7": [
    "project-number-guessing-game",
    "chapter-summary",
    "transition"
  ],
  "9.1": [
    "functions",
    "calling-functions",
    "arguments",
    "chapter-opening-stop-repeating-yourself",
    "chapter-roadmap"
  ],
  "9.2": [
    "parameters"
  ],
  "9.3": [
    "return-values"
  ],
  "9.4": [
    "local-scope"
  ],
  "9.5": [
    "global-scope"
  ],
  "9.6": [
    "call-stack"
  ],
  "9.7": [
    "pure-functions",
    "side-effects"
  ],
  "9.8": [
    "project",
    "chapter-summary",
    "transition"
  ],
  "10.1": [
    "lists-arrays",
    "indexing",
    "chapter-opening-one-variable-isn-t-enough",
    "chapter-roadmap"
  ],
  "10.2": [
    "tuples"
  ],
  "10.3": [
    "dictionaries-maps"
  ],
  "10.4": [
    "sets"
  ],
  "10.5": [
    "iteration"
  ],
  "10.6": [
    "nested-collections",
    "choosing-collections"
  ],
  "10.7": [
    "project",
    "chapter-summary",
    "transition"
  ],
  "11.1": [
    "string-processing",
    "chapter-opening-making-data-survive",
    "chapter-roadmap"
  ],
  "11.2": [
    "reading-files"
  ],
  "11.3": [
    "writing-files"
  ],
  "11.4": [
    "json"
  ],
  "11.5": [
    "csv"
  ],
  "11.6": [
    "file-paths"
  ],
  "11.7": [
    "text-vs-binary"
  ],
  "11.8": [
    "serialization"
  ],
  "11.9": [
    "project",
    "chapter-summary",
    "transition"
  ],
  "12.1": [
    "syntax-errors",
    "exception-handling",
    "chapter-opening-programs-fail",
    "chapter-roadmap"
  ],
  "12.2": [
    "runtime-errors"
  ],
  "12.3": [
    "logical-errors"
  ],
  "12.4": [
    "exceptions"
  ],
  "12.5": [
    "validation"
  ],
  "12.6": [
    "assertions"
  ],
  "12.7": [
    "fail-fast-thinking"
  ],
  "12.8": [
    "practice",
    "chapter-summary",
    "transition"
  ],
  "13.1": [
    "error-messages",
    "systematic-debugging",
    "chapter-opening-finding-out-why-software-is-wrong",
    "chapter-roadmap"
  ],
  "13.2": [
    "reproducing-bugs"
  ],
  "13.3": [
    "logging"
  ],
  "13.4": [
    "breakpoints"
  ],
  "13.5": [
    "stack-traces"
  ],
  "13.6": [
    "watches"
  ],
  "13.7": [
    "stepping"
  ],
  "13.8": [
    "lab",
    "chapter-summary",
    "transition"
  ],
  "14.1": [
    "imports",
    "chapter-opening-one-file-isn-t-enough",
    "chapter-roadmap"
  ],
  "14.2": [
    "modules"
  ],
  "14.3": [
    "packages"
  ],
  "14.4": [
    "namespaces"
  ],
  "14.5": [
    "virtual-environments"
  ],
  "14.6": [
    "pip-pypi"
  ],
  "14.7": [
    "requirements-txt"
  ],
  "14.9": [
    "project",
    "chapter-summary",
    "transition"
  ],
  "15.1": [
    "project-multi-file-expense-tracker",
    "planning-a-multi-file-program",
    "chapter-opening-from-syntax-to-fluency",
    "chapter-roadmap",
    "unit-closing-transition"
  ],
  "16.1": [
    "what-is-a-set",
    "chapter-opening-a-new-language-for-ideas-you-already-have",
    "chapter-roadmap"
  ],
  "16.2": [
    "set-operations"
  ],
  "16.3": [
    "venn-diagrams"
  ],
  "16.8": [
    "practice",
    "chapter-summary"
  ],
  "17.1": [
    "direct-proof",
    "quantifiers",
    "implication-vs-equivalence",
    "chapter-opening-from-believing-to-knowing",
    "chapter-roadmap"
  ],
  "17.2": [
    "proof-by-contradiction"
  ],
  "17.3": [
    "counterexamples"
  ],
  "17.4": [
    "mathematical-induction"
  ],
  "17.5": [
    "propositions-predicates"
  ],
  "17.6": [
    "practice",
    "chapter-summary",
    "transition"
  ],
  "18.1": [
    "permutations-combinations",
    "birthday-paradox",
    "chapter-opening-counting-without-listing",
    "chapter-roadmap"
  ],
  "18.2": [
    "multiplication-principle"
  ],
  "18.3": [
    "basic-probability"
  ],
  "18.4": [
    "conditional-probability"
  ],
  "18.5": [
    "expected-value"
  ],
  "18.6": [
    "independence"
  ],
  "18.7": [
    "practice",
    "chapter-summary",
    "transition"
  ],
  "19.1": [
    "mean",
    "statistical-significance-in-plain-words",
    "practice",
    "chapter-opening-reading-numbers-honestly",
    "chapter-roadmap"
  ],
  "19.2": [
    "variance-standard-deviation"
  ],
  "19.3": [
    "distributions"
  ],
  "19.4": [
    "sampling-bias"
  ],
  "19.5": [
    "median-mode"
  ],
  "19.6": [
    "correlation-vs-causation"
  ],
  "19.7": [
    "chapter-summary",
    "transition"
  ],
  "20.1": [
    "vectors",
    "practice",
    "chapter-opening-two-last-tools",
    "chapter-roadmap"
  ],
  "20.2": [
    "matrices"
  ],
  "20.3": [
    "derivatives"
  ],
  "20.4": [
    "gradient-descent"
  ],
  "20.6": [
    "matrix-multiplication-in-practice"
  ],
  "20.8": [
    "chapter-summary",
    "unit-closing-transition"
  ],
  "21.1": [
    "state",
    "modeling",
    "relationships",
    "chapter-opening-how-do-we-model-a-large-problem",
    "chapter-roadmap"
  ],
  "21.2": [
    "behavior"
  ],
  "21.3": [
    "entities"
  ],
  "21.4": [
    "responsibilities"
  ],
  "21.5": [
    "practice",
    "summary",
    "transition-we-have-the-model-now-let-s-represent-it-in-code"
  ],
  "22.1": [
    "classes",
    "attributes",
    "methods",
    "chapter-opening-turning-models-into-code",
    "chapter-roadmap"
  ],
  "22.2": [
    "instances"
  ],
  "22.3": [
    "constructors"
  ],
  "22.4": [
    "identity"
  ],
  "22.5": [
    "equality"
  ],
  "22.6": [
    "project",
    "summary",
    "transition-objects-work-but-their-internals-shouldn-t-be-exposed-everywhere"
  ],
  "23.1": [
    "public-interfaces",
    "chapter-opening-hiding-complexity",
    "chapter-roadmap"
  ],
  "23.2": [
    "internal-state"
  ],
  "23.3": [
    "invariants"
  ],
  "23.4": [
    "information-hiding"
  ],
  "23.5": [
    "abstraction-boundaries"
  ],
  "23.6": [
    "project",
    "summary",
    "transition-what-if-multiple-objects-share-related-behavior"
  ],
  "24.1": [
    "is-a",
    "problems-with-inheritance",
    "chapter-opening-reusing-related-behavior",
    "chapter-roadmap"
  ],
  "24.2": [
    "overriding"
  ],
  "24.3": [
    "super"
  ],
  "24.4": [
    "polymorphism"
  ],
  "24.5": [
    "abstract-classes-interfaces",
    "base-derived-classes"
  ],
  "24.6": [
    "practice",
    "summary",
    "transition-inheritance-helps-but-often-combining-objects-is-safer"
  ],
  "25.1": [
    "has-a",
    "chapter-opening-building-objects-from-smaller-objects",
    "chapter-roadmap"
  ],
  "25.2": [
    "association"
  ],
  "25.3": [
    "aggregation"
  ],
  "25.4": [
    "composition",
    "composition-vs-inheritance"
  ],
  "25.5": [
    "delegation"
  ],
  "25.6": [
    "practice",
    "summary",
    "transition-we-know-the-mechanics-now-we-need-principles-for-good-design"
  ],
  "26.1": [
    "srp",
    "principles-together",
    "chapter-opening-making-designs-easier-to-change",
    "chapter-roadmap"
  ],
  "26.2": [
    "ocp"
  ],
  "26.3": [
    "lsp"
  ],
  "26.4": [
    "isp"
  ],
  "26.5": [
    "dip"
  ],
  "26.6": [
    "refactoring-lab",
    "summary",
    "transition-principles-tell-us-what-good-design-looks-like-now-let-s-improve-existing-code"
  ],
  "27.1": [
    "naming",
    "readability",
    "chapter-opening-working-code-can-still-be-bad-code",
    "chapter-roadmap"
  ],
  "27.2": [
    "duplication"
  ],
  "27.3": [
    "long-methods"
  ],
  "27.4": [
    "god-objects"
  ],
  "27.5": [
    "coupling"
  ],
  "27.6": [
    "cohesion"
  ],
  "27.7": [
    "code-smells"
  ],
  "27.8": [
    "safe-refactoring"
  ],
  "27.9": [
    "lab",
    "summary",
    "transition-some-design-problems-appear-again-and-again"
  ],
  "28.1": [
    "factory",
    "when-not-to-use-patterns",
    "chapter-opening-learning-from-recurring-design-problems",
    "chapter-roadmap"
  ],
  "28.2": [
    "builder"
  ],
  "28.3": [
    "adapter"
  ],
  "28.4": [
    "facade"
  ],
  "28.5": [
    "decorator"
  ],
  "28.6": [
    "strategy"
  ],
  "28.7": [
    "observer"
  ],
  "28.8": [
    "dependency-injection"
  ],
  "28.9": [
    "repository"
  ],
  "28.10": [
    "exercise",
    "summary",
    "transition-we-know-individual-patterns-how-do-we-design-an-entire-feature"
  ],
  "29.1": [
    "requirements",
    "responsibilities",
    "trade-offs",
    "chapter-opening-designing-before-coding",
    "chapter-roadmap"
  ],
  "29.2": [
    "entities"
  ],
  "29.3": [
    "relationships"
  ],
  "29.4": [
    "interfaces"
  ],
  "29.5": [
    "uml-class-diagrams"
  ],
  "29.6": [
    "sequence-diagrams"
  ],
  "29.7": [
    "state-diagrams"
  ],
  "29.8": [
    "project-design-three-systems",
    "summary",
    "transition-let-s-combine-everything"
  ],
  "30.1": [
    "project-parking-management-system",
    "domain-modeling",
    "class-design",
    "interfaces",
    "composition",
    "solid-pass",
    "refactoring",
    "chapter-opening-ten-chapters-one-build",
    "chapter-roadmap",
    "summary",
    "unit-transition-organizing-large-software"
  ],
  "31.1": [
    "big-o",
    "measuring-work",
    "input-size",
    "growth-rates",
    "chapter-opening-it-works-isn-t-the-whole-story",
    "chapter-roadmap"
  ],
  "31.2": [
    "time-complexity"
  ],
  "31.3": [
    "space-complexity"
  ],
  "31.4": [
    "best-average-worst"
  ],
  "31.5": [
    "big",
    "big-ω",
    "big-omega"
  ],
  "31.6": [
    "big-θ",
    "big-theta"
  ],
  "31.7": [
    "amortized-analysis"
  ],
  "31.8": [
    "practice",
    "summary",
    "transition-to-improve-efficiency-we-first-need-better-ways-to-organize-data"
  ],
  "32.1": [
    "memory-layout",
    "traversal",
    "complexity",
    "chapter-opening-the-simplest-way-to-store-many-values",
    "chapter-roadmap"
  ],
  "32.2": [
    "indexing"
  ],
  "32.3": [
    "insertion",
    "deletion"
  ],
  "32.4": [
    "dynamic-arrays"
  ],
  "32.5": [
    "strings"
  ],
  "32.6": [
    "practice",
    "summary",
    "transition-arrays-are-fast-to-index-but-inserting-can-be-expensive"
  ],
  "33.1": [
    "nodes",
    "links",
    "complexity",
    "chapter-opening-what-if-data-doesn-t-need-to-be-contiguous",
    "chapter-roadmap"
  ],
  "33.2": [
    "singly-linked"
  ],
  "33.3": [
    "doubly-linked"
  ],
  "33.4": [
    "circular",
    "arrays-vs-lists"
  ],
  "33.5": [
    "implementation",
    "summary",
    "transition-sometimes-what-matters-isn-t-where-data-lives-but-the-order-we-access-it"
  ],
  "34.1": [
    "stack",
    "lifo",
    "fifo",
    "uses",
    "chapter-opening-access-rules-not-new-storage",
    "chapter-roadmap"
  ],
  "34.2": [
    "queue"
  ],
  "34.3": [
    "deque"
  ],
  "34.4": [
    "priority-queue-intuition"
  ],
  "34.5": [
    "project-balanced-symbols-job-fairness",
    "summary",
    "transition-a-stack-also-appears-naturally-when-functions-call-themselves"
  ],
  "35.1": [
    "base-case",
    "tracing",
    "chapter-opening-solving-a-problem-using-smaller-versions-of-itself",
    "chapter-roadmap"
  ],
  "35.2": [
    "recursive-case",
    "recursive-thinking"
  ],
  "35.3": [
    "call-stack"
  ],
  "35.4": [
    "recursion-trees",
    "recursion-vs-iteration"
  ],
  "35.5": [
    "tail-recursion"
  ],
  "35.6": [
    "practice",
    "summary",
    "transition-we-ve-seen-different-ways-to-access-data-can-we-find-data-almost-instantly"
  ],
  "36.1": [
    "hash-functions",
    "keys-values",
    "complexity",
    "chapter-opening-finding-data-without-searching-everything",
    "chapter-roadmap"
  ],
  "36.2": [
    "hash-tables"
  ],
  "36.3": [
    "collisions"
  ],
  "36.4": [
    "load-factor"
  ],
  "36.5": [
    "chaining"
  ],
  "36.6": [
    "open-addressing"
  ],
  "36.7": [
    "implementation",
    "summary",
    "transition-hash-tables-are-great-for-lookup-but-what-about-hierarchical-data"
  ],
  "37.1": [
    "binary-trees",
    "terminology",
    "chapter-opening-data-with-parents-children-hierarchy",
    "chapter-roadmap"
  ],
  "37.2": [
    "traversals"
  ],
  "37.3": [
    "bst"
  ],
  "37.4": [
    "balanced-trees"
  ],
  "37.5": [
    "avl"
  ],
  "37.6": [
    "red-black-intuition"
  ],
  "37.7": [
    "practice",
    "summary",
    "transition-some-trees-are-designed-around-priority-rather-than-search"
  ],
  "38.1": [
    "min-heap",
    "binary-heaps",
    "operations",
    "complexity",
    "chapter-opening-the-tree-that-only-answers-one-question",
    "chapter-roadmap"
  ],
  "38.2": [
    "max-heap"
  ],
  "38.3": [
    "heapify"
  ],
  "38.4": [
    "priority-queues"
  ],
  "38.5": [
    "project-task-scheduler-top-k-dashboard",
    "summary",
    "transition-we-can-organize-data-by-priority-what-if-we-want-everything-ordered"
  ],
  "39.1": [
    "bubble-sort",
    "comparing-algorithms",
    "chapter-opening-putting-data-in-order",
    "chapter-roadmap"
  ],
  "39.2": [
    "selection-sort"
  ],
  "39.3": [
    "insertion-sort"
  ],
  "39.4": [
    "merge-sort"
  ],
  "39.5": [
    "quick-sort"
  ],
  "39.6": [
    "heap-sort"
  ],
  "39.7": [
    "stability"
  ],
  "39.8": [
    "comparison-vs-non-comparison"
  ],
  "39.9": [
    "project-sort-visualizer-benchmark",
    "summary",
    "transition-once-data-is-ordered-finding-things-can-become-much-faster"
  ],
  "40.1": [
    "linear-search",
    "invariants",
    "complexity",
    "chapter-opening-finding-what-we-need",
    "chapter-roadmap"
  ],
  "40.2": [
    "binary-search-intuition"
  ],
  "40.3": [
    "binary-search-on-answer"
  ],
  "40.4": [
    "practice",
    "implementation",
    "summary",
    "transition-arrays-trees-and-lists-model-structure-but-what-about-arbitrary-relationships"
  ],
  "41.1": [
    "representation",
    "vertices-edges",
    "directed-undirected",
    "weighted-graphs",
    "shortest-paths",
    "chapter-opening-modeling-networks-relationships",
    "chapter-roadmap"
  ],
  "41.2": [
    "bfs"
  ],
  "41.3": [
    "dfs"
  ],
  "41.4": [
    "topological-sort"
  ],
  "41.5": [
    "dijkstra"
  ],
  "41.6": [
    "connected-components"
  ],
  "41.7": [
    "minimum-spanning-trees"
  ],
  "41.8": [
    "kruskal"
  ],
  "41.9": [
    "prim"
  ],
  "41.10": [
    "project-city-navigator",
    "summary",
    "transition-we-know-individual-algorithms-now-let-s-recognize-patterns-across-problems"
  ],
  "42.1": [
    "two-pointers",
    "intervals",
    "chapter-opening-stop-memorizing-problems-recognize-their-shape",
    "chapter-roadmap"
  ],
  "42.2": [
    "sliding-window"
  ],
  "42.3": [
    "prefix-sum"
  ],
  "42.4": [
    "divide-conquer"
  ],
  "42.5": [
    "fast-slow"
  ],
  "42.6": [
    "monotonic-stack"
  ],
  "42.7": [
    "choosing-patterns"
  ],
  "42.8": [
    "practice",
    "summary",
    "transition-some-problems-let-us-make-the-best-choice-right-now"
  ],
  "43.1": [
    "greedy-choice-property",
    "when-greedy-works",
    "when-greedy-fails",
    "chapter-opening-commit-early-never-look-back",
    "chapter-roadmap"
  ],
  "43.2": [
    "global-optimum",
    "local-choices"
  ],
  "43.3": [
    "practice",
    "summary",
    "transition-what-if-we-can-t-know-which-choice-is-best-until-we-explore"
  ],
  "44.1": [
    "decision-trees",
    "templates",
    "chapter-opening-try-explore-undo",
    "chapter-roadmap"
  ],
  "44.2": [
    "choose",
    "explore",
    "undo"
  ],
  "44.3": [
    "pruning"
  ],
  "44.4": [
    "project-n-queens-visualizer",
    "summary",
    "transition-exploration-works-but-we-often-solve-the-same-smaller-problem-repeatedly"
  ],
  "45.1": [
    "overlapping-subproblems",
    "transitions",
    "recognizing-dp",
    "chapter-opening-remembering-work-we-ve-already-done",
    "chapter-roadmap"
  ],
  "45.2": [
    "optimal-substructure"
  ],
  "45.3": [
    "memoization"
  ],
  "45.4": [
    "tabulation"
  ],
  "45.5": [
    "state"
  ],
  "45.6": [
    "space-optimization"
  ],
  "45.7": [
    "practice",
    "summary",
    "transition-general-structures-aren-t-always-enough-for-specialized-problems"
  ],
  "46.1": [
    "tries",
    "choosing-structures",
    "chapter-opening-purpose-built-tools",
    "chapter-roadmap"
  ],
  "46.2": [
    "union-find"
  ],
  "46.3": [
    "bloom-filters"
  ],
  "46.4": [
    "segment-trees"
  ],
  "46.5": [
    "fenwick-trees"
  ],
  "46.6": [
    "project-autocomplete-friend-circles",
    "summary",
    "transition-fast-algorithms-are-useful-only-if-they-re-also-correct"
  ],
  "47.1": [
    "preconditions",
    "specifications",
    "correctness-arguments",
    "chapter-opening-how-do-we-know-it-always-works",
    "chapter-roadmap"
  ],
  "47.2": [
    "postconditions"
  ],
  "47.3": [
    "loop-invariants"
  ],
  "47.4": [
    "termination"
  ],
  "47.5": [
    "practice",
    "summary",
    "transition-we-now-have-all-the-major-pieces-let-s-put-them-together"
  ],
  "48.1": [
    "project-data-structures-library",
    "choosing-data-structures",
    "choosing-algorithms",
    "complexity-trade-offs",
    "correctness",
    "chapter-opening-eighteen-chapters-one-decision-process",
    "chapter-roadmap",
    "summary",
    "unit-transition-efficient-but-still-a-black-box"
  ],
  "49.1": [
    "instruction-sets",
    "pipelines",
    "chapter-opening-let-s-open-the-black-box",
    "chapter-roadmap"
  ],
  "49.2": [
    "registers"
  ],
  "49.3": [
    "assembly"
  ],
  "49.4": [
    "cache-hierarchy"
  ],
  "49.5": [
    "machine-instructions"
  ],
  "49.6": [
    "multicore"
  ],
  "49.7": [
    "risc-vs-cisc"
  ],
  "49.8": [
    "branch-prediction"
  ],
  "49.9": [
    "locality"
  ],
  "49.10": [
    "simd"
  ],
  "49.11": [
    "lab-trace-the-tiny-cpu",
    "summary",
    "transition-the-cpu-executes-instructions-but-where-does-a-running-program-live"
  ],
  "50.1": [
    "stack",
    "chapter-opening-where-does-your-program-actually-live",
    "chapter-roadmap"
  ],
  "50.2": [
    "heap"
  ],
  "50.3": [
    "static-global-storage"
  ],
  "50.4": [
    "references-pointers"
  ],
  "50.5": [
    "memory-safety",
    "process-memory-layout"
  ],
  "50.6": [
    "allocation"
  ],
  "50.7": [
    "garbage-collection"
  ],
  "50.8": [
    "memory-leaks"
  ],
  "50.9": [
    "dangling-pointers"
  ],
  "50.10": [
    "ownership-borrowing"
  ],
  "50.11": [
    "practice",
    "summary",
    "transition-we-ve-seen-how-programs-live-in-memory-but-how-are-programming-languages-built"
  ],
  "51.1": [
    "grammars",
    "chapter-opening-who-builds-the-language-we-re-programming-in",
    "chapter-roadmap"
  ],
  "51.2": [
    "tokens-lexing"
  ],
  "51.3": [
    "parsing"
  ],
  "51.4": [
    "asts"
  ],
  "51.5": [
    "type-systems"
  ],
  "51.6": [
    "runtime-models"
  ],
  "51.7": [
    "regular-languages"
  ],
  "51.8": [
    "finite-state-machines"
  ],
  "51.9": [
    "regular-expressions"
  ],
  "51.10": [
    "context-free-grammars"
  ],
  "51.11": [
    "static-vs-dynamic"
  ],
  "51.12": [
    "ir"
  ],
  "51.13": [
    "code-generation"
  ],
  "51.14": [
    "optimization"
  ],
  "51.15": [
    "project-build-a-tiny-expression-language",
    "summary",
    "transition-programs-need-more-than-a-cpu-and-memory-something-must-manage-the-machine"
  ],
  "52.1": [
    "kernel",
    "ipc",
    "chapter-opening-the-manager-of-the-computer",
    "chapter-roadmap"
  ],
  "52.2": [
    "system-calls"
  ],
  "52.3": [
    "processes"
  ],
  "52.4": [
    "threads"
  ],
  "52.5": [
    "scheduling"
  ],
  "52.6": [
    "virtual-memory"
  ],
  "52.7": [
    "filesystems"
  ],
  "52.8": [
    "user-vs-kernel-mode"
  ],
  "52.9": [
    "paging"
  ],
  "52.10": [
    "page-faults"
  ],
  "52.11": [
    "os-responsibilities"
  ],
  "52.12": [
    "context-switching"
  ],
  "52.13": [
    "lab-watch-the-os-work",
    "summary",
    "transition-the-os-lets-many-things-run-what-happens-when-they-run-together"
  ],
  "53.1": [
    "race-conditions",
    "threads",
    "shared-state",
    "chapter-opening-more-than-one-thing-at-a-time",
    "chapter-roadmap"
  ],
  "53.2": [
    "critical-sections"
  ],
  "53.3": [
    "mutexes"
  ],
  "53.4": [
    "semaphores"
  ],
  "53.5": [
    "atomics-deadlocks"
  ],
  "53.6": [
    "concurrency-vs-parallelism"
  ],
  "53.7": [
    "thread-safety"
  ],
  "53.8": [
    "condition-variables"
  ],
  "53.9": [
    "futures-promises"
  ],
  "53.10": [
    "async-programming"
  ],
  "53.11": [
    "project-concurrent-web-crawler-producer-consumer",
    "summary",
    "transition-now-let-s-use-these-os-capabilities-directly"
  ],
  "54.1": [
    "file-descriptors",
    "resource-management",
    "chapter-opening-talking-directly-to-the-operating-system",
    "chapter-roadmap"
  ],
  "54.2": [
    "process-control"
  ],
  "54.3": [
    "pipes"
  ],
  "54.4": [
    "signals"
  ],
  "54.5": [
    "sockets"
  ],
  "54.6": [
    "memory-mapped-files"
  ],
  "54.7": [
    "project-mini-shell-echo-server",
    "summary",
    "unit-transition-we-understand-one-computer-deeply"
  ],
  "55.1": [
    "osi-tcp-ip",
    "subnetting",
    "chapter-opening-how-does-one-computer-reach-another",
    "chapter-roadmap"
  ],
  "55.2": [
    "mac"
  ],
  "55.3": [
    "ip"
  ],
  "55.4": [
    "networks"
  ],
  "55.5": [
    "routers"
  ],
  "55.6": [
    "nat"
  ],
  "55.7": [
    "ports"
  ],
  "55.8": [
    "ethernet"
  ],
  "55.9": [
    "arp"
  ],
  "55.10": [
    "dhcp"
  ],
  "55.11": [
    "firewalls"
  ],
  "55.12": [
    "ipv4-ipv6"
  ],
  "55.13": [
    "practice",
    "summary",
    "transition-we-can-reach-another-machine-how-do-applications-reliably-exchange-data"
  ],
  "56.1": [
    "tcp",
    "transport-layer",
    "handshake",
    "chapter-opening-getting-data-from-application-a-to-application-b",
    "chapter-roadmap"
  ],
  "56.2": [
    "reliability"
  ],
  "56.3": [
    "ordering"
  ],
  "56.4": [
    "udp",
    "tcp-vs-udp"
  ],
  "56.5": [
    "sockets"
  ],
  "56.6": [
    "flow-control"
  ],
  "56.7": [
    "congestion-control"
  ],
  "56.8": [
    "project-reliable-chat-over-both-transports",
    "summary",
    "transition-connections-use-addresses-humans-prefer-names"
  ],
  "57.1": [
    "domains",
    "internet-architecture",
    "chapter-opening-how-does-google-com-become-a-destination",
    "chapter-roadmap"
  ],
  "57.2": [
    "resolution"
  ],
  "57.3": [
    "caching"
  ],
  "57.4": [
    "routing"
  ],
  "57.5": [
    "dns-records"
  ],
  "57.6": [
    "dns",
    "recursive-resolvers",
    "authoritative-servers"
  ],
  "57.7": [
    "trace-exercise",
    "summary",
    "transition-we-found-the-server-now-how-does-a-browser-talk-to-it"
  ],
  "58.1": [
    "request-response",
    "clients-servers",
    "chapter-opening-the-conversation-behind-the-web",
    "chapter-roadmap"
  ],
  "58.2": [
    "methods"
  ],
  "58.3": [
    "headers"
  ],
  "58.4": [
    "status-codes"
  ],
  "58.5": [
    "cookies"
  ],
  "58.6": [
    "caching"
  ],
  "58.7": [
    "https"
  ],
  "58.8": [
    "http-1-1",
    "http-2",
    "http-3"
  ],
  "58.9": [
    "browser-server-journey"
  ],
  "58.10": [
    "websockets"
  ],
  "58.11": [
    "project-raw-http-client-mini-server",
    "summary",
    "transition-http-gives-us-communication-how-should-applications-structure-that-communication"
  ],
  "59.1": [
    "rest",
    "errors",
    "chapter-opening-software-talking-to-software",
    "chapter-roadmap"
  ],
  "59.2": [
    "resources"
  ],
  "59.3": [
    "crud"
  ],
  "59.4": [
    "validation"
  ],
  "59.5": [
    "pagination"
  ],
  "59.6": [
    "filtering-sorting"
  ],
  "59.7": [
    "versioning"
  ],
  "59.8": [
    "idempotency"
  ],
  "59.9": [
    "authentication"
  ],
  "59.10": [
    "authorization"
  ],
  "59.11": [
    "apis"
  ],
  "59.12": [
    "openapi"
  ],
  "59.13": [
    "graphql"
  ],
  "59.14": [
    "grpc"
  ],
  "59.15": [
    "project-design-build-a-rest-api",
    "summary",
    "unit-transition-applications-talk-nicely-now-where-does-their-data-live-between-requests"
  ],
  "60.1": [
    "databases",
    "comparison",
    "chapter-opening-why-not-just-store-everything-in-files",
    "chapter-roadmap"
  ],
  "60.2": [
    "dbms"
  ],
  "60.3": [
    "tables"
  ],
  "60.4": [
    "rows",
    "columns"
  ],
  "60.5": [
    "keys"
  ],
  "60.6": [
    "non-relational",
    "relational"
  ],
  "60.7": [
    "practice",
    "summary",
    "transition-we-understand-databases-now-we-need-to-talk-to-one"
  ],
  "61.1": [
    "select",
    "where",
    "aggregation",
    "chapter-opening-speaking-the-language-of-relational-data",
    "chapter-roadmap"
  ],
  "61.2": [
    "insert"
  ],
  "61.3": [
    "update"
  ],
  "61.4": [
    "delete"
  ],
  "61.5": [
    "join"
  ],
  "61.6": [
    "group-by"
  ],
  "61.7": [
    "ctes"
  ],
  "61.8": [
    "subqueries"
  ],
  "61.9": [
    "window-functions"
  ],
  "61.10": [
    "transactions"
  ],
  "61.11": [
    "practice",
    "summary",
    "transition-sql-lets-us-query-tables-but-who-decides-how-those-tables-should-look"
  ],
  "62.1": [
    "entities",
    "attributes",
    "chapter-opening-design-before-create-table",
    "chapter-roadmap"
  ],
  "62.2": [
    "relationships"
  ],
  "62.3": [
    "foreign-keys",
    "primary-keys"
  ],
  "62.4": [
    "constraints"
  ],
  "62.5": [
    "normalization"
  ],
  "62.6": [
    "er-diagrams"
  ],
  "62.7": [
    "denormalization"
  ],
  "62.8": [
    "project-model-normalize-a-domain",
    "summary",
    "transition-we-can-design-and-query-a-database-but-why-are-some-queries-fast-and-others-slow"
  ],
  "63.1": [
    "disk-pages",
    "wal",
    "chapter-opening-looking-inside-the-database-engine",
    "chapter-roadmap"
  ],
  "63.2": [
    "b-trees"
  ],
  "63.3": [
    "indexes"
  ],
  "63.4": [
    "query-planning",
    "execution-plans"
  ],
  "63.5": [
    "sequential-scans"
  ],
  "63.6": [
    "index-scans"
  ],
  "63.7": [
    "buffer-cache"
  ],
  "63.8": [
    "lab-make-a-query-fast",
    "summary",
    "transition-databases-are-shared-what-happens-when-many-users-change-data-at-once"
  ],
  "64.1": [
    "acid",
    "transactions",
    "chapter-opening-two-users-one-piece-of-data",
    "chapter-roadmap"
  ],
  "64.2": [
    "isolation"
  ],
  "64.3": [
    "locks"
  ],
  "64.4": [
    "deadlocks"
  ],
  "64.5": [
    "dirty-reads"
  ],
  "64.6": [
    "non-repeatable-reads"
  ],
  "64.7": [
    "phantom-reads"
  ],
  "64.8": [
    "mvcc"
  ],
  "64.9": [
    "project-break-it-yourself",
    "summary",
    "transition-a-correct-database-is-good-a-production-database-must-also-survive-failure-and-scale"
  ],
  "65.1": [
    "connection-pools",
    "recovery",
    "choosing-a-database",
    "chapter-opening-taking-the-database-to-production",
    "chapter-roadmap"
  ],
  "65.2": [
    "migrations"
  ],
  "65.3": [
    "backups"
  ],
  "65.4": [
    "replication"
  ],
  "65.5": [
    "partitioning"
  ],
  "65.6": [
    "sharding"
  ],
  "65.7": [
    "read-replicas"
  ],
  "65.8": [
    "failover"
  ],
  "65.9": [
    "nosql-models"
  ],
  "65.10": [
    "architecture-exercise",
    "summary",
    "unit-transition-our-systems-store-valuable-information-now-who-protects-it"
  ],
  "66.1": [
    "availability",
    "confidentiality",
    "integrity",
    "chapter-opening-what-are-we-actually-protecting",
    "chapter-roadmap"
  ],
  "66.2": [
    "threats",
    "assets",
    "threat-modeling"
  ],
  "66.3": [
    "vulnerabilities"
  ],
  "66.4": [
    "risk"
  ],
  "66.5": [
    "least-privilege"
  ],
  "66.6": [
    "attack-surface"
  ],
  "66.7": [
    "defense-in-depth"
  ],
  "66.8": [
    "exercise-map-a-real-system",
    "summary",
    "transition-we-know-what-needs-protection-now-how-do-we-protect-the-data-itself"
  ],
  "67.1": [
    "hashing",
    "choosing-the-correct-tool",
    "chapter-opening-protecting-information-with-mathematics",
    "chapter-roadmap"
  ],
  "67.2": [
    "symmetric-encryption"
  ],
  "67.3": [
    "asymmetric-encryption"
  ],
  "67.4": [
    "digital-signatures"
  ],
  "67.5": [
    "tls"
  ],
  "67.6": [
    "salts"
  ],
  "67.7": [
    "key-derivation"
  ],
  "67.8": [
    "certificates",
    "pki"
  ],
  "67.9": [
    "why-not-to-invent-crypto"
  ],
  "67.10": [
    "practice",
    "chapter-summary",
    "closing-transition-we-can-protect-data-but-who-should-be-allowed-to-access-it"
  ],
  "68.1": [
    "password-hashing",
    "authentication-vs-authorization",
    "openid-connect",
    "chapter-opening-who-are-you-and-what-can-you-do",
    "chapter-roadmap"
  ],
  "68.2": [
    "sessions"
  ],
  "68.3": [
    "cookies"
  ],
  "68.4": [
    "jwt"
  ],
  "68.5": [
    "oauth"
  ],
  "68.6": [
    "mfa"
  ],
  "68.7": [
    "rbac"
  ],
  "68.8": [
    "abac"
  ],
  "68.9": [
    "tokens",
    "access-refresh-tokens"
  ],
  "68.10": [
    "project-authentication-permissions-system",
    "chapter-summary",
    "closing-transition-a-login-system-is-not-the-same-thing-as-a-secure-application"
  ],
  "69.1": [
    "input-validation",
    "chapter-opening-users-must-log-in-does-not-mean-we-re-secure",
    "roadmap"
  ],
  "69.2": [
    "sql-injection"
  ],
  "69.3": [
    "xss"
  ],
  "69.4": [
    "csrf"
  ],
  "69.5": [
    "cors"
  ],
  "69.6": [
    "secrets"
  ],
  "69.7": [
    "dependency-security"
  ],
  "69.8": [
    "rate-limiting"
  ],
  "69.9": [
    "ssrf"
  ],
  "69.10": [
    "path-traversal"
  ],
  "69.11": [
    "broken-access-control"
  ],
  "69.12": [
    "secure-headers"
  ],
  "69.13": [
    "owasp-top-10"
  ],
  "69.14": [
    "lab-attack-and-harden-a-bookstore",
    "summary",
    "transition-secure-software-still-has-to-be-understandable-and-usable-by-humans"
  ],
  "70.1": [
    "usability",
    "user-goals",
    "chapter-opening-software-is-built-for-people",
    "chapter-roadmap"
  ],
  "70.2": [
    "feedback"
  ],
  "70.3": [
    "accessibility"
  ],
  "70.4": [
    "error-prevention"
  ],
  "70.5": [
    "information-architecture"
  ],
  "70.6": [
    "interaction-design"
  ],
  "70.7": [
    "responsive-design"
  ],
  "70.8": [
    "exercise-heuristic-evaluation",
    "summary",
    "transition-interfaces-aren-t-just-buttons-and-text-computers-also-produce-rich-visual-worlds"
  ],
  "71.1": [
    "pixels",
    "interactive-graphics",
    "chapter-opening-from-pixels-to-worlds",
    "chapter-roadmap"
  ],
  "71.2": [
    "coordinates"
  ],
  "71.3": [
    "colors"
  ],
  "71.4": [
    "transformations"
  ],
  "71.5": [
    "rendering-pipeline"
  ],
  "71.6": [
    "raster-vs-vector"
  ],
  "71.7": [
    "project-bouncing-block-explorer",
    "summary",
    "unit-transition-we-now-understand-functional-secure-usable-software-but-real-software-is-rarely-built-alone"
  ],
  "72.1": [
    "repository",
    "remotes",
    "opening-what-happens-when-multiple-developers-change-the-same-code",
    "roadmap"
  ],
  "72.2": [
    "commits"
  ],
  "72.3": [
    "branches"
  ],
  "72.4": [
    "merge"
  ],
  "72.5": [
    "pull-requests",
    "pull-push"
  ],
  "72.6": [
    "working-tree-staging"
  ],
  "72.7": [
    "rebase"
  ],
  "72.8": [
    "conflicts"
  ],
  "72.9": [
    "tags-releases"
  ],
  "72.10": [
    "gitignore"
  ],
  "72.11": [
    "lab",
    "team-workflow",
    "summary",
    "transition-teams-can-collaborate-on-code-but-how-do-they-know-what-to-build"
  ],
  "73.1": [
    "functional-requirements",
    "problem-understanding",
    "opening-building-the-right-thing",
    "roadmap"
  ],
  "73.2": [
    "non-functional-requirements"
  ],
  "73.3": [
    "user-stories"
  ],
  "73.4": [
    "acceptance-criteria"
  ],
  "73.5": [
    "stakeholders"
  ],
  "73.6": [
    "constraints"
  ],
  "73.7": [
    "scope-creep",
    "scope"
  ],
  "73.8": [
    "project",
    "summary",
    "transition-requirements-tell-us-what-should-work-testing-checks-whether-it-does"
  ],
  "74.1": [
    "unit",
    "e2e",
    "opening-it-worked-on-my-machine-isn-t-enough",
    "roadmap"
  ],
  "74.2": [
    "integration"
  ],
  "74.3": [
    "good-tests"
  ],
  "74.4": [
    "fakes-mocks"
  ],
  "74.5": [
    "regression"
  ],
  "74.6": [
    "test-pyramid"
  ],
  "74.7": [
    "property-based"
  ],
  "74.8": [
    "performance"
  ],
  "74.9": [
    "coverage"
  ],
  "74.10": [
    "project",
    "summary",
    "transition-individual-components-can-be-tested-but-how-should-the-whole-application-be-organized"
  ],
  "75.1": [
    "separation-of-concerns",
    "layered",
    "opening-designing-the-shape-of-an-application",
    "roadmap"
  ],
  "75.2": [
    "coupling"
  ],
  "75.3": [
    "cohesion"
  ],
  "75.4": [
    "client-server"
  ],
  "75.5": [
    "modular-monolith"
  ],
  "75.6": [
    "trade-offs",
    "microservices"
  ],
  "75.7": [
    "choosing-architecture"
  ],
  "75.8": [
    "mvc"
  ],
  "75.9": [
    "clean-hexagonal"
  ],
  "75.10": [
    "exercise",
    "summary",
    "transition-we-know-how-to-structure-the-product-how-does-a-team-actually-build-it"
  ],
  "76.1": [
    "planning",
    "issues",
    "opening-from-idea-to-working-software",
    "roadmap"
  ],
  "76.2": [
    "iteration"
  ],
  "76.3": [
    "agile"
  ],
  "76.4": [
    "code-review"
  ],
  "76.5": [
    "technical-debt"
  ],
  "76.6": [
    "documentation"
  ],
  "76.7": [
    "scrum"
  ],
  "76.8": [
    "estimation"
  ],
  "76.9": [
    "kanban"
  ],
  "76.10": [
    "lab",
    "summary",
    "transition-humans-repeat-build-and-release-work-constantly-let-s-automate-it"
  ],
  "77.1": [
    "build",
    "rolling",
    "blue-green",
    "canary",
    "opening-from-commit-to-production-automatically",
    "roadmap"
  ],
  "77.2": [
    "lint"
  ],
  "77.3": [
    "tests"
  ],
  "77.4": [
    "ci"
  ],
  "77.5": [
    "delivery-deployment"
  ],
  "77.6": [
    "rollback"
  ],
  "77.7": [
    "artifacts"
  ],
  "77.8": [
    "environments"
  ],
  "77.9": [
    "packaging"
  ],
  "77.10": [
    "project",
    "summary",
    "transition-the-pipeline-can-deploy-software-but-how-do-we-package-it-consistently"
  ],
  "78.1": [
    "deployment-problems",
    "isolation",
    "opening-works-here-breaks-there",
    "roadmap"
  ],
  "78.2": [
    "environment-variables"
  ],
  "78.3": [
    "docker"
  ],
  "78.4": [
    "images"
  ],
  "78.5": [
    "containers"
  ],
  "78.6": [
    "reverse-proxies"
  ],
  "78.7": [
    "dockerfile"
  ],
  "78.8": [
    "volumes"
  ],
  "78.9": [
    "networking"
  ],
  "78.10": [
    "compose"
  ],
  "78.11": [
    "registries"
  ],
  "78.12": [
    "orchestration",
    "kubernetes-overview"
  ],
  "78.13": [
    "lab",
    "summary",
    "transition-we-can-package-the-application-where-do-we-actually-run-it"
  ],
  "79.1": [
    "compute",
    "iac",
    "opening-running-software-without-owning-the-datacenter",
    "roadmap"
  ],
  "79.2": [
    "storage"
  ],
  "79.3": [
    "networking"
  ],
  "79.4": [
    "managed-databases"
  ],
  "79.5": [
    "iam"
  ],
  "79.6": [
    "availability-zones",
    "regions"
  ],
  "79.7": [
    "autoscaling"
  ],
  "79.8": [
    "serverless"
  ],
  "79.9": [
    "object-storage"
  ],
  "79.10": [
    "cloud-computing"
  ],
  "79.11": [
    "secrets"
  ],
  "79.12": [
    "exercise",
    "summary",
    "transition-our-application-is-live-how-do-we-know-whether-it-s-healthy"
  ],
  "80.1": [
    "logs",
    "observability",
    "opening-your-users-found-a-bug-at-2-am-now-what",
    "roadmap"
  ],
  "80.2": [
    "metrics"
  ],
  "80.3": [
    "traces"
  ],
  "80.4": [
    "alerts"
  ],
  "80.5": [
    "root-cause-analysis"
  ],
  "80.6": [
    "health-checks"
  ],
  "80.7": [
    "dashboards"
  ],
  "80.8": [
    "sli",
    "slo",
    "sla"
  ],
  "80.9": [
    "incident-response"
  ],
  "80.10": [
    "postmortems"
  ],
  "80.11": [
    "lab",
    "summary",
    "unit-transition-we-can-build-test-deploy-and-operate-software-but-everything-we-ve-built-can-eventually-reach-a-point-where-one-machine-is-not-enough"
  ],
  "81.1": [
    "functional-requirements",
    "non-functional-requirements",
    "trade-offs",
    "opening-what-changes-when-millions-of-people-use-our-software",
    "roadmap"
  ],
  "81.2": [
    "scale"
  ],
  "81.3": [
    "latency"
  ],
  "81.4": [
    "throughput"
  ],
  "81.5": [
    "availability"
  ],
  "81.6": [
    "capacity-estimation"
  ],
  "81.7": [
    "reliability"
  ],
  "81.8": [
    "durability"
  ],
  "81.9": [
    "practice",
    "summary",
    "transition-we-know-what-scale-means-now-how-do-we-actually-scale"
  ],
  "82.1": [
    "vertical-scaling",
    "bottlenecks",
    "opening-one-server-isn-t-enough-anymore",
    "roadmap"
  ],
  "82.2": [
    "horizontal-scaling"
  ],
  "82.3": [
    "stateless-services"
  ],
  "82.4": [
    "load-balancing"
  ],
  "82.5": [
    "reverse-proxies"
  ],
  "82.6": [
    "service-discovery"
  ],
  "82.7": [
    "exercise",
    "summary",
    "transition-more-servers-help-but-repeating-expensive-work-still-wastes-resources"
  ],
  "83.1": [
    "browser-cache",
    "consistency",
    "opening-why-do-the-same-expensive-work-twice",
    "roadmap"
  ],
  "83.2": [
    "cdn"
  ],
  "83.3": [
    "application-cache"
  ],
  "83.4": [
    "distributed-cache"
  ],
  "83.5": [
    "cache",
    "invalidation"
  ],
  "83.6": [
    "cache-aside"
  ],
  "83.7": [
    "write-through"
  ],
  "83.8": [
    "ttl"
  ],
  "83.9": [
    "eviction"
  ],
  "83.10": [
    "exercise",
    "summary",
    "transition-some-work-doesn-t-need-to-happen-during-the-user-s-request-at-all"
  ],
  "84.1": [
    "queues",
    "idempotency",
    "opening-do-it-later-can-be-a-powerful-design",
    "roadmap"
  ],
  "84.2": [
    "producers"
  ],
  "84.3": [
    "consumers"
  ],
  "84.4": [
    "pub-sub"
  ],
  "84.5": [
    "events"
  ],
  "84.6": [
    "retries"
  ],
  "84.7": [
    "sync-vs-async"
  ],
  "84.8": [
    "ordering"
  ],
  "84.9": [
    "at-least-once"
  ],
  "84.10": [
    "dlq"
  ],
  "84.11": [
    "project",
    "summary",
    "transition-once-components-run-independently-across-machines-we-enter-distributed-systems"
  ],
  "85.1": [
    "partial-failure",
    "why-distribution-is-hard",
    "opening-one-system-many-machines-new-problems",
    "roadmap"
  ],
  "85.2": [
    "network-partitions"
  ],
  "85.3": [
    "replication"
  ],
  "85.4": [
    "strong-consistency"
  ],
  "85.5": [
    "eventual-consistency"
  ],
  "85.6": [
    "cap"
  ],
  "85.7": [
    "pacelc"
  ],
  "85.8": [
    "distributed-clocks",
    "distributed-time"
  ],
  "85.9": [
    "exercise",
    "summary",
    "transition-independent-machines-can-disagree-how-do-they-coordinate"
  ],
  "86.1": [
    "leader-election",
    "coordination-problem",
    "opening-how-do-machines-agree",
    "roadmap"
  ],
  "86.2": [
    "quorums"
  ],
  "86.3": [
    "consensus"
  ],
  "86.4": [
    "distributed-locks"
  ],
  "86.5": [
    "leases"
  ],
  "86.6": [
    "raft"
  ],
  "86.7": [
    "simulator",
    "summary",
    "transition-agreement-helps-but-machines-will-still-fail"
  ],
  "87.1": [
    "timeouts",
    "opening-assume-something-will-break",
    "roadmap"
  ],
  "87.2": [
    "retries"
  ],
  "87.3": [
    "backoff"
  ],
  "87.4": [
    "circuit-breakers"
  ],
  "87.5": [
    "rate-limiting"
  ],
  "87.6": [
    "graceful-degradation"
  ],
  "87.7": [
    "bulkheads"
  ],
  "87.8": [
    "health-checks"
  ],
  "87.9": [
    "failover"
  ],
  "87.10": [
    "practice",
    "summary",
    "transition-we-have-all-the-building-blocks-let-s-design-one-complete-large-system"
  ],
  "88.1": [
    "requirements",
    "caching",
    "observability",
    "trade-offs",
    "chapter-opening-from-blank-page-to-complete-architecture",
    "chapter-roadmap"
  ],
  "88.2": [
    "capacity-estimation"
  ],
  "88.3": [
    "api-gateway"
  ],
  "88.4": [
    "load-balancing"
  ],
  "88.5": [
    "application-services"
  ],
  "88.6": [
    "api-design"
  ],
  "88.7": [
    "database-design"
  ],
  "88.8": [
    "queues"
  ],
  "88.9": [
    "search"
  ],
  "88.10": [
    "cdn"
  ],
  "88.11": [
    "object-storage"
  ],
  "88.12": [
    "failure-modes",
    "reliability"
  ],
  "88.13": [
    "project-design-a-large-system-end-to-end",
    "chapter-summary",
    "unit-closing-transition"
  ],
  "89.1": [
    "search",
    "llms",
    "limitations",
    "opening-can-a-computer-learn",
    "roadmap"
  ],
  "89.2": [
    "reasoning",
    "knowledge-representation"
  ],
  "89.3": [
    "machine-learning"
  ],
  "89.4": [
    "neural-networks"
  ],
  "89.5": [
    "classical-ai"
  ],
  "89.6": [
    "supervised-learning"
  ],
  "89.7": [
    "unsupervised-learning"
  ],
  "89.8": [
    "training-vs-inference"
  ],
  "89.9": [
    "overfitting"
  ],
  "89.10": [
    "project",
    "summary",
    "transition-ai-is-one-specialized-area-computing-itself-also-runs-on-many-different-platforms"
  ],
  "90.1": [
    "mobile",
    "choosing-platforms",
    "project",
    "opening-a-laptop-isn-t-the-only-kind-of-computer",
    "roadmap"
  ],
  "90.2": [
    "embedded"
  ],
  "90.3": [
    "iot"
  ],
  "90.4": [
    "serverless"
  ],
  "90.5": [
    "edge",
    "gpu-computing"
  ],
  "90.6": [
    "cloud"
  ],
  "90.7": [
    "summary",
    "transition-technology-doesn-t-exist-in-isolation-it-affects-real-people"
  ],
  "91.1": [
    "privacy",
    "data-ownership",
    "opening-just-because-we-can-build-it-should-we",
    "roadmap"
  ],
  "91.2": [
    "bias"
  ],
  "91.3": [
    "accessibility"
  ],
  "91.4": [
    "intellectual-property"
  ],
  "91.5": [
    "sustainability"
  ],
  "91.6": [
    "professional-responsibility"
  ],
  "91.7": [
    "open-source"
  ],
  "91.8": [
    "licensing"
  ],
  "91.9": [
    "responsible-ai"
  ],
  "91.10": [
    "case-study",
    "summary",
    "unit-transition"
  ],
  "92.1": [
    "read-before-changing",
    "entry-points",
    "verify-behavior",
    "opening-here-s-the-repository-fix-this-bug",
    "roadmap"
  ],
  "92.2": [
    "trace-execution"
  ],
  "92.3": [
    "dependencies"
  ],
  "92.4": [
    "boundaries"
  ],
  "92.5": [
    "small-safe-changes"
  ],
  "92.6": [
    "repository-orientation"
  ],
  "92.7": [
    "search-references"
  ],
  "92.8": [
    "existing-tests"
  ],
  "92.9": [
    "lab",
    "summary",
    "transition-sometimes-the-codebase-isn-t-just-unfamiliar-it-s-old-fragile-and-difficult-to-change"
  ],
  "93.1": [
    "characterization-tests",
    "legacy-code",
    "opening-software-doesn-t-stay-new-forever",
    "roadmap"
  ],
  "93.2": [
    "safe-refactoring"
  ],
  "93.3": [
    "backward-compatibility"
  ],
  "93.4": [
    "data-migrations"
  ],
  "93.5": [
    "deprecation"
  ],
  "93.6": [
    "feature-flags"
  ],
  "93.7": [
    "incremental-migration"
  ],
  "93.8": [
    "dependency-upgrades"
  ],
  "93.9": [
    "project",
    "summary",
    "transition-maintaining-software-also-means-explaining-decisions-to-other-humans"
  ],
  "94.1": [
    "readme",
    "communicating-trade-offs",
    "opening-code-isn-t-the-only-thing-engineers-write",
    "roadmap"
  ],
  "94.2": [
    "design-documents"
  ],
  "94.3": [
    "comments"
  ],
  "94.4": [
    "bug-reports"
  ],
  "94.5": [
    "pr-descriptions"
  ],
  "94.6": [
    "adrs"
  ],
  "94.7": [
    "api-documentation"
  ],
  "94.8": [
    "runbooks"
  ],
  "94.9": [
    "release-notes"
  ],
  "94.10": [
    "practice",
    "summary",
    "unit-transition"
  ],
  "95.1": [
    "define-the-problem",
    "identify-users",
    "define-scope",
    "apis",
    "chapter-opening-don-t-touch-the-keyboard-yet",
    "roadmap"
  ],
  "95.2": [
    "gather-requirements"
  ],
  "95.3": [
    "architecture"
  ],
  "95.4": [
    "database-design"
  ],
  "95.5": [
    "milestones"
  ],
  "95.6": [
    "identify-risks"
  ],
  "95.7": [
    "trade-offs"
  ],
  "95.8": [
    "deliverable-design-document",
    "summary",
    "transition-we-know-what-we-re-building-and-why-now-we-earn-the-right-to-code"
  ],
  "96.1": [
    "interface",
    "foundation",
    "business-logic",
    "opening-design-becomes-software",
    "roadmap"
  ],
  "96.2": [
    "backend"
  ],
  "96.3": [
    "api"
  ],
  "96.4": [
    "database"
  ],
  "96.5": [
    "authentication"
  ],
  "96.6": [
    "authorization"
  ],
  "96.7": [
    "testing"
  ],
  "96.8": [
    "ci-cd"
  ],
  "96.9": [
    "deployment"
  ],
  "96.10": [
    "observability",
    "summary",
    "transition-it-works-now-let-s-try-to-break-it"
  ],
  "97.1": [
    "load-testing",
    "measure-again",
    "opening-working-software-isn-t-finished-software",
    "roadmap"
  ],
  "97.2": [
    "bottlenecks"
  ],
  "97.3": [
    "failure-simulation"
  ],
  "97.4": [
    "security-review"
  ],
  "97.5": [
    "refactoring"
  ],
  "97.6": [
    "baselines"
  ],
  "97.7": [
    "profiling"
  ],
  "97.8": [
    "cpu"
  ],
  "97.9": [
    "memory"
  ],
  "97.10": [
    "database"
  ],
  "97.11": [
    "capacity",
    "summary",
    "transition-we-ve-built-and-hardened-it-now-let-s-show-the-world-what-we-built"
  ],
  "98.1": [
    "readme",
    "portfolio-presentation",
    "final-review",
    "opening-engineering-work-needs-evidence",
    "roadmap"
  ],
  "98.2": [
    "architecture-diagram"
  ],
  "98.3": [
    "database-diagram"
  ],
  "98.4": [
    "api-documentation"
  ],
  "98.5": [
    "production-deployment"
  ],
  "98.6": [
    "testing-documentation"
  ],
  "98.7": [
    "trade-offs"
  ],
  "98.8": [
    "demo"
  ],
  "98.9": [
    "screenshots"
  ],
  "98.10": [
    "release-notes",
    "unit-transition"
  ],
  "99.1": [
    "clarify",
    "edge-cases",
    "explain",
    "implement",
    "trade-offs",
    "opening-an-interview-is-more-than-getting-the-answer",
    "roadmap"
  ],
  "99.2": [
    "examples"
  ],
  "99.3": [
    "brute-force"
  ],
  "99.4": [
    "optimize"
  ],
  "99.5": [
    "understand"
  ],
  "99.6": [
    "test"
  ],
  "99.7": [
    "complexity",
    "summary",
    "transition-we-know-the-method-now-we-need-repetition"
  ],
  "100.1": [
    "arrays",
    "strings",
    "two-pointers",
    "sliding-window",
    "stacks-queues",
    "linked-lists",
    "opening-turning-knowledge-into-speed-recognition",
    "roadmap"
  ],
  "100.2": [
    "hashing"
  ],
  "100.3": [
    "trees"
  ],
  "100.4": [
    "graphs"
  ],
  "100.5": [
    "binary-search"
  ],
  "100.6": [
    "backtracking"
  ],
  "100.7": [
    "dp"
  ],
  "100.8": [
    "heaps"
  ],
  "100.9": [
    "intervals"
  ],
  "100.10": [
    "greedy",
    "summary",
    "transition-coding-isn-t-the-only-thing-interviewers-ask"
  ],
  "101.1": [
    "oop",
    "dsa",
    "memory",
    "opening-can-you-explain-what-you-ve-learned",
    "roadmap"
  ],
  "101.2": [
    "operating-systems"
  ],
  "101.3": [
    "networking"
  ],
  "101.4": [
    "databases"
  ],
  "101.5": [
    "concurrency"
  ],
  "101.6": [
    "security"
  ],
  "101.7": [
    "architecture"
  ],
  "101.8": [
    "programming",
    "languages",
    "summary",
    "transition-fundamentals-test-knowledge-design-interviews-test-how-you-structure-problems"
  ],
  "102.1": [
    "requirements",
    "use-cases",
    "responsibilities",
    "opening-turning-requirements-into-objects",
    "roadmap"
  ],
  "102.2": [
    "entities"
  ],
  "102.3": [
    "relationships"
  ],
  "102.4": [
    "interfaces"
  ],
  "102.5": [
    "trade-offs"
  ],
  "102.6": [
    "class-diagrams"
  ],
  "102.7": [
    "extensibility",
    "summary",
    "transition-that-s-design-inside-one-application-now-let-s-design-at-system-scale"
  ],
  "103.1": [
    "requirements",
    "reliability",
    "trade-offs",
    "opening-designing-while-someone-watches-your-thinking",
    "roadmap"
  ],
  "103.2": [
    "scale"
  ],
  "103.3": [
    "apis"
  ],
  "103.4": [
    "data"
  ],
  "103.5": [
    "architecture"
  ],
  "103.6": [
    "application-scaling",
    "database-scaling"
  ],
  "103.7": [
    "failure-modes"
  ],
  "103.8": [
    "caching"
  ],
  "103.9": [
    "queues"
  ],
  "103.10": [
    "consistency"
  ],
  "103.11": [
    "observability",
    "summary",
    "transition-technical-skill-is-only-part-of-working-on-a-team"
  ],
  "104.1": [
    "star",
    "story-bank",
    "impact",
    "opening-how-do-you-actually-work-with-people",
    "roadmap"
  ],
  "104.2": [
    "projects"
  ],
  "104.3": [
    "failure"
  ],
  "104.4": [
    "conflict"
  ],
  "104.5": [
    "ownership"
  ],
  "104.6": [
    "technical-decisions"
  ],
  "104.7": [
    "leadership"
  ],
  "104.8": [
    "ambiguity"
  ],
  "104.9": [
    "learning-from-mistakes",
    "summary",
    "transition-we-ve-practiced-every-piece-separately-there-s-only-one-thing-left"
  ],
  "105.1": [
    "coding-round",
    "targeted-revision",
    "opening-this-time-it-s-the-whole-interview"
  ],
  "105.2": [
    "cs-fundamentals-round"
  ],
  "105.3": [
    "low-level-design-round"
  ],
  "105.4": [
    "system-design-round"
  ],
  "105.5": [
    "behavioral-round"
  ],
  "105.6": [
    "portfolio-walkthrough"
  ],
  "105.7": [
    "resume-walkthrough"
  ],
  "105.8": [
    "review-performance",
    "final-preparation-roadmap",
    "identify-weak-areas",
    "repeat-weak-rounds",
    "final-job-readiness-check",
    "course-closing"
  ]
};

export const csProgressV5LessonMap: Record<string, string[]> = {
  "1.3": [
    "1.1"
  ],
  "1.4": [
    "1.2"
  ],
  "1.5": [
    "1.3"
  ],
  "1.6": [
    "1.4"
  ],
  "1.8": [
    "1.7"
  ],
  "2.3": [
    "2.1"
  ],
  "2.4": [
    "2.2"
  ],
  "2.5": [
    "2.3"
  ],
  "2.7": [
    "2.4"
  ],
  "2.6": [
    "2.5"
  ],
  "2.8": [
    "2.6"
  ],
  "2.9": [
    "2.7"
  ],
  "3.3": [
    "3.1"
  ],
  "3.5": [
    "3.2"
  ],
  "3.4": [
    "3.3"
  ],
  "3.6": [
    "3.4"
  ],
  "3.7": [
    "3.5"
  ],
  "3.8": [
    "3.6"
  ],
  "4.3": [
    "4.1"
  ],
  "4.4": [
    "4.2"
  ],
  "4.5": [
    "4.3"
  ],
  "4.6": [
    "4.4"
  ],
  "4.7": [
    "4.5"
  ],
  "4.8": [
    "4.6"
  ],
  "4.9": [
    "4.7"
  ],
  "4.10": [
    "4.8"
  ],
  "4.11": [
    "4.9"
  ],
  "5.3": [
    "5.1"
  ],
  "5.4": [
    "5.2"
  ],
  "5.9": [
    "5.3"
  ],
  "5.10": [
    "5.4"
  ],
  "5.11": [
    "5.5"
  ],
  "5.12": [
    "5.6"
  ],
  "5.5": [
    "5.7"
  ],
  "5.6": [
    "5.8"
  ],
  "5.13": [
    "5.9"
  ],
  "5.14": [
    "5.10"
  ],
  "5.17": [
    "5.11"
  ],
  "5.7": [
    "5.1"
  ],
  "5.8": [
    "5.2"
  ],
  "5.15": [
    "5.1"
  ],
  "6.3": [
    "6.1"
  ],
  "6.4": [
    "6.2"
  ],
  "6.6": [
    "6.3"
  ],
  "6.7": [
    "6.4"
  ],
  "6.8": [
    "6.5"
  ],
  "6.9": [
    "6.6"
  ],
  "6.10": [
    "6.7"
  ],
  "6.12": [
    "6.8"
  ],
  "6.5": [
    "6.1"
  ],
  "7.4": [
    "7.1"
  ],
  "7.5": [
    "7.2"
  ],
  "7.6": [
    "7.3"
  ],
  "7.8": [
    "7.4"
  ],
  "7.9": [
    "7.5"
  ],
  "7.10": [
    "7.6"
  ],
  "7.11": [
    "7.7"
  ],
  "7.12": [
    "7.8"
  ],
  "7.14": [
    "7.9"
  ],
  "7.3": [
    "7.1"
  ],
  "7.7": [
    "7.1"
  ],
  "8.5": [
    "8.1"
  ],
  "8.6": [
    "8.2"
  ],
  "8.8": [
    "8.3"
  ],
  "8.9": [
    "8.4"
  ],
  "8.10": [
    "8.5"
  ],
  "8.3": [
    "8.6"
  ],
  "8.13": [
    "8.7"
  ],
  "8.4": [
    "8.1"
  ],
  "8.7": [
    "8.1"
  ],
  "8.11": [
    "8.5"
  ],
  "9.3": [
    "9.1"
  ],
  "9.5": [
    "9.2"
  ],
  "9.7": [
    "9.3"
  ],
  "9.8": [
    "9.4"
  ],
  "9.9": [
    "9.5"
  ],
  "9.10": [
    "9.6"
  ],
  "9.12": [
    "9.7"
  ],
  "9.14": [
    "9.8"
  ],
  "9.4": [
    "9.1"
  ],
  "9.6": [
    "9.1"
  ],
  "9.11": [
    "9.7"
  ],
  "10.3": [
    "10.1"
  ],
  "10.5": [
    "10.2"
  ],
  "10.6": [
    "10.3"
  ],
  "10.7": [
    "10.4"
  ],
  "10.8": [
    "10.5"
  ],
  "10.9": [
    "10.6"
  ],
  "10.12": [
    "10.7"
  ],
  "10.4": [
    "10.1"
  ],
  "10.10": [
    "10.6"
  ],
  "11.3": [
    "11.1"
  ],
  "11.5": [
    "11.2"
  ],
  "11.6": [
    "11.3"
  ],
  "11.8": [
    "11.4"
  ],
  "11.9": [
    "11.5"
  ],
  "11.4": [
    "11.6"
  ],
  "11.7": [
    "11.7"
  ],
  "11.10": [
    "11.8"
  ],
  "11.12": [
    "11.9"
  ],
  "12.3": [
    "12.1"
  ],
  "12.4": [
    "12.2"
  ],
  "12.5": [
    "12.3"
  ],
  "12.6": [
    "12.4"
  ],
  "12.8": [
    "12.5"
  ],
  "12.9": [
    "12.6"
  ],
  "12.10": [
    "12.7"
  ],
  "12.12": [
    "12.8"
  ],
  "12.7": [
    "12.1"
  ],
  "13.4": [
    "13.1"
  ],
  "13.3": [
    "13.2"
  ],
  "13.5": [
    "13.3"
  ],
  "13.6": [
    "13.4"
  ],
  "13.9": [
    "13.5"
  ],
  "13.8": [
    "13.6"
  ],
  "13.7": [
    "13.7"
  ],
  "13.12": [
    "13.8"
  ],
  "13.10": [
    "13.1"
  ],
  "14.4": [
    "14.1"
  ],
  "14.3": [
    "14.2"
  ],
  "14.5": [
    "14.3"
  ],
  "14.6": [
    "14.4"
  ],
  "14.8": [
    "14.5"
  ],
  "14.7": [
    "14.6"
  ],
  "14.9": [
    "14.7"
  ],
  "14.11": [
    "14.9"
  ],
  "15.4": [
    "15.1"
  ],
  "15.3": [
    "15.1"
  ],
  "16.3": [
    "16.1"
  ],
  "16.4": [
    "16.2"
  ],
  "16.5": [
    "16.3"
  ],
  "16.7": [
    "16.8"
  ],
  "17.6": [
    "17.1"
  ],
  "17.7": [
    "17.2"
  ],
  "17.8": [
    "17.3"
  ],
  "17.9": [
    "17.4"
  ],
  "17.3": [
    "17.5"
  ],
  "17.11": [
    "17.6"
  ],
  "17.4": [
    "17.1"
  ],
  "17.5": [
    "17.1"
  ],
  "18.4": [
    "18.1"
  ],
  "18.3": [
    "18.2"
  ],
  "18.5": [
    "18.3"
  ],
  "18.6": [
    "18.4"
  ],
  "18.8": [
    "18.5"
  ],
  "18.7": [
    "18.6"
  ],
  "18.11": [
    "18.7"
  ],
  "18.9": [
    "18.1"
  ],
  "19.3": [
    "19.1"
  ],
  "19.5": [
    "19.2"
  ],
  "19.6": [
    "19.3"
  ],
  "19.8": [
    "19.4"
  ],
  "19.4": [
    "19.5"
  ],
  "19.7": [
    "19.6"
  ],
  "19.9": [
    "19.1"
  ],
  "19.11": [
    "19.1"
  ],
  "20.3": [
    "20.1"
  ],
  "20.4": [
    "20.2"
  ],
  "20.6": [
    "20.3"
  ],
  "20.7": [
    "20.4"
  ],
  "20.5": [
    "20.6"
  ],
  "20.9": [
    "20.1"
  ],
  "21.5": [
    "21.1"
  ],
  "21.6": [
    "21.2"
  ],
  "21.4": [
    "21.3"
  ],
  "21.7": [
    "21.4"
  ],
  "21.10": [
    "21.5"
  ],
  "21.3": [
    "21.1"
  ],
  "21.8": [
    "21.1"
  ],
  "22.3": [
    "22.1"
  ],
  "22.4": [
    "22.2"
  ],
  "22.7": [
    "22.3"
  ],
  "22.8": [
    "22.4"
  ],
  "22.9": [
    "22.5"
  ],
  "22.11": [
    "22.6"
  ],
  "22.5": [
    "22.1"
  ],
  "22.6": [
    "22.1"
  ],
  "23.4": [
    "23.1"
  ],
  "23.3": [
    "23.2"
  ],
  "23.6": [
    "23.3"
  ],
  "23.5": [
    "23.4"
  ],
  "23.7": [
    "23.5"
  ],
  "23.9": [
    "23.6"
  ],
  "24.3": [
    "24.1"
  ],
  "24.5": [
    "24.2"
  ],
  "24.6": [
    "24.3"
  ],
  "24.8": [
    "24.4"
  ],
  "24.7": [
    "24.5"
  ],
  "24.11": [
    "24.6"
  ],
  "24.4": [
    "24.5"
  ],
  "24.9": [
    "24.1"
  ],
  "25.3": [
    "25.1"
  ],
  "25.4": [
    "25.2"
  ],
  "25.5": [
    "25.3"
  ],
  "25.6": [
    "25.4"
  ],
  "25.7": [
    "25.5"
  ],
  "25.10": [
    "25.6"
  ],
  "25.8": [
    "25.4"
  ],
  "26.3": [
    "26.1"
  ],
  "26.4": [
    "26.2"
  ],
  "26.5": [
    "26.3"
  ],
  "26.6": [
    "26.4"
  ],
  "26.7": [
    "26.5"
  ],
  "26.10": [
    "26.6"
  ],
  "26.8": [
    "26.1"
  ],
  "27.4": [
    "27.1"
  ],
  "27.5": [
    "27.2"
  ],
  "27.6": [
    "27.3"
  ],
  "27.7": [
    "27.4"
  ],
  "27.8": [
    "27.5"
  ],
  "27.9": [
    "27.6"
  ],
  "27.10": [
    "27.7"
  ],
  "27.11": [
    "27.8"
  ],
  "27.13": [
    "27.9"
  ],
  "27.3": [
    "27.1"
  ],
  "28.3": [
    "28.1"
  ],
  "28.4": [
    "28.2"
  ],
  "28.5": [
    "28.3"
  ],
  "28.6": [
    "28.4"
  ],
  "28.7": [
    "28.5"
  ],
  "28.8": [
    "28.6"
  ],
  "28.9": [
    "28.7"
  ],
  "28.10": [
    "28.8"
  ],
  "28.11": [
    "28.9"
  ],
  "28.14": [
    "28.10"
  ],
  "28.12": [
    "28.1"
  ],
  "29.3": [
    "29.1"
  ],
  "29.4": [
    "29.2"
  ],
  "29.5": [
    "29.3"
  ],
  "29.7": [
    "29.4"
  ],
  "29.8": [
    "29.5"
  ],
  "29.9": [
    "29.6"
  ],
  "29.10": [
    "29.7"
  ],
  "29.13": [
    "29.8"
  ],
  "29.6": [
    "29.1"
  ],
  "29.11": [
    "29.1"
  ],
  "30.10": [
    "30.1"
  ],
  "30.3": [
    "30.1"
  ],
  "30.4": [
    "30.1"
  ],
  "30.5": [
    "30.1"
  ],
  "30.6": [
    "30.1"
  ],
  "30.7": [
    "30.1"
  ],
  "30.8": [
    "30.1"
  ],
  "31.8": [
    "31.1"
  ],
  "31.5": [
    "31.2"
  ],
  "31.6": [
    "31.3"
  ],
  "31.11": [
    "31.4"
  ],
  "31.9": [
    "31.5"
  ],
  "31.10": [
    "31.6"
  ],
  "31.12": [
    "31.7"
  ],
  "31.14": [
    "31.8"
  ],
  "31.3": [
    "31.1"
  ],
  "31.4": [
    "31.1"
  ],
  "31.7": [
    "31.1"
  ],
  "32.3": [
    "32.1"
  ],
  "32.4": [
    "32.2"
  ],
  "32.6": [
    "32.3"
  ],
  "32.8": [
    "32.4"
  ],
  "32.9": [
    "32.5"
  ],
  "32.12": [
    "32.6"
  ],
  "32.5": [
    "32.1"
  ],
  "32.7": [
    "32.3"
  ],
  "32.10": [
    "32.1"
  ],
  "33.3": [
    "33.1"
  ],
  "33.5": [
    "33.2"
  ],
  "33.6": [
    "33.3"
  ],
  "33.7": [
    "33.4"
  ],
  "33.11": [
    "33.5"
  ],
  "33.4": [
    "33.1"
  ],
  "33.8": [
    "33.1"
  ],
  "33.9": [
    "33.4"
  ],
  "34.3": [
    "34.1"
  ],
  "34.5": [
    "34.2"
  ],
  "34.7": [
    "34.3"
  ],
  "34.8": [
    "34.4"
  ],
  "34.11": [
    "34.5"
  ],
  "34.4": [
    "34.1"
  ],
  "34.6": [
    "34.1"
  ],
  "34.9": [
    "34.1"
  ],
  "35.4": [
    "35.1"
  ],
  "35.5": [
    "35.2"
  ],
  "35.6": [
    "35.3"
  ],
  "35.8": [
    "35.4"
  ],
  "35.9": [
    "35.5"
  ],
  "35.12": [
    "35.6"
  ],
  "35.3": [
    "35.2"
  ],
  "35.7": [
    "35.1"
  ],
  "35.10": [
    "35.4"
  ],
  "36.3": [
    "36.1"
  ],
  "36.4": [
    "36.2"
  ],
  "36.6": [
    "36.3"
  ],
  "36.9": [
    "36.4"
  ],
  "36.7": [
    "36.5"
  ],
  "36.8": [
    "36.6"
  ],
  "36.12": [
    "36.7"
  ],
  "36.5": [
    "36.1"
  ],
  "36.10": [
    "36.1"
  ],
  "37.4": [
    "37.1"
  ],
  "37.5": [
    "37.2"
  ],
  "37.6": [
    "37.3"
  ],
  "37.7": [
    "37.4"
  ],
  "37.8": [
    "37.5"
  ],
  "37.9": [
    "37.6"
  ],
  "37.11": [
    "37.7"
  ],
  "37.3": [
    "37.1"
  ],
  "38.5": [
    "38.1"
  ],
  "38.6": [
    "38.2"
  ],
  "38.7": [
    "38.3"
  ],
  "38.3": [
    "38.4"
  ],
  "38.11": [
    "38.5"
  ],
  "38.4": [
    "38.1"
  ],
  "38.8": [
    "38.1"
  ],
  "38.9": [
    "38.1"
  ],
  "39.3": [
    "39.1"
  ],
  "39.4": [
    "39.2"
  ],
  "39.5": [
    "39.3"
  ],
  "39.6": [
    "39.4"
  ],
  "39.7": [
    "39.5"
  ],
  "39.8": [
    "39.6"
  ],
  "39.9": [
    "39.7"
  ],
  "39.10": [
    "39.8"
  ],
  "39.13": [
    "39.9"
  ],
  "39.11": [
    "39.1"
  ],
  "40.3": [
    "40.1"
  ],
  "40.4": [
    "40.2"
  ],
  "40.7": [
    "40.3"
  ],
  "40.10": [
    "40.4"
  ],
  "40.5": [
    "40.4"
  ],
  "40.6": [
    "40.1"
  ],
  "40.8": [
    "40.1"
  ],
  "41.6": [
    "41.1"
  ],
  "41.7": [
    "41.2"
  ],
  "41.8": [
    "41.3"
  ],
  "41.10": [
    "41.4"
  ],
  "41.12": [
    "41.5"
  ],
  "41.9": [
    "41.6"
  ],
  "41.13": [
    "41.7"
  ],
  "41.14": [
    "41.8"
  ],
  "41.15": [
    "41.9"
  ],
  "41.17": [
    "41.10"
  ],
  "41.3": [
    "41.1"
  ],
  "41.4": [
    "41.1"
  ],
  "41.5": [
    "41.1"
  ],
  "41.11": [
    "41.1"
  ],
  "42.3": [
    "42.1"
  ],
  "42.5": [
    "42.2"
  ],
  "42.6": [
    "42.3"
  ],
  "42.7": [
    "42.4"
  ],
  "42.4": [
    "42.5"
  ],
  "42.8": [
    "42.6"
  ],
  "42.10": [
    "42.7"
  ],
  "42.12": [
    "42.8"
  ],
  "42.9": [
    "42.1"
  ],
  "43.5": [
    "43.1"
  ],
  "43.4": [
    "43.2"
  ],
  "43.9": [
    "43.3"
  ],
  "43.3": [
    "43.2"
  ],
  "43.6": [
    "43.1"
  ],
  "43.7": [
    "43.1"
  ],
  "44.3": [
    "44.1"
  ],
  "44.4": [
    "44.2"
  ],
  "44.7": [
    "44.3"
  ],
  "44.10": [
    "44.4"
  ],
  "44.5": [
    "44.2"
  ],
  "44.6": [
    "44.2"
  ],
  "44.8": [
    "44.1"
  ],
  "45.3": [
    "45.1"
  ],
  "45.4": [
    "45.2"
  ],
  "45.7": [
    "45.3"
  ],
  "45.8": [
    "45.4"
  ],
  "45.5": [
    "45.5"
  ],
  "45.9": [
    "45.6"
  ],
  "45.12": [
    "45.7"
  ],
  "45.6": [
    "45.1"
  ],
  "45.10": [
    "45.1"
  ],
  "46.3": [
    "46.1"
  ],
  "46.4": [
    "46.2"
  ],
  "46.5": [
    "46.3"
  ],
  "46.6": [
    "46.4"
  ],
  "46.7": [
    "46.5"
  ],
  "46.10": [
    "46.6"
  ],
  "46.8": [
    "46.1"
  ],
  "47.4": [
    "47.1"
  ],
  "47.5": [
    "47.2"
  ],
  "47.6": [
    "47.3"
  ],
  "47.7": [
    "47.4"
  ],
  "47.10": [
    "47.5"
  ],
  "47.3": [
    "47.1"
  ],
  "47.8": [
    "47.1"
  ],
  "48.8": [
    "48.1"
  ],
  "48.3": [
    "48.1"
  ],
  "48.4": [
    "48.1"
  ],
  "48.5": [
    "48.1"
  ],
  "48.6": [
    "48.1"
  ],
  "49.3": [
    "49.1"
  ],
  "49.5": [
    "49.2"
  ],
  "49.6": [
    "49.3"
  ],
  "49.10": [
    "49.4"
  ],
  "49.4": [
    "49.5"
  ],
  "49.12": [
    "49.6"
  ],
  "49.7": [
    "49.7"
  ],
  "49.9": [
    "49.8"
  ],
  "49.11": [
    "49.9"
  ],
  "49.13": [
    "49.10"
  ],
  "49.15": [
    "49.11"
  ],
  "49.8": [
    "49.1"
  ],
  "50.4": [
    "50.1"
  ],
  "50.5": [
    "50.2"
  ],
  "50.6": [
    "50.3"
  ],
  "50.7": [
    "50.4"
  ],
  "50.12": [
    "50.5"
  ],
  "50.8": [
    "50.6"
  ],
  "50.9": [
    "50.7"
  ],
  "50.10": [
    "50.8"
  ],
  "50.11": [
    "50.9"
  ],
  "50.13": [
    "50.10"
  ],
  "50.15": [
    "50.11"
  ],
  "50.3": [
    "50.5"
  ],
  "51.3": [
    "51.1"
  ],
  "51.4": [
    "51.2"
  ],
  "51.8": [
    "51.3"
  ],
  "51.10": [
    "51.4"
  ],
  "51.11": [
    "51.5"
  ],
  "51.13": [
    "51.6"
  ],
  "51.5": [
    "51.7"
  ],
  "51.6": [
    "51.8"
  ],
  "51.7": [
    "51.9"
  ],
  "51.9": [
    "51.10"
  ],
  "51.12": [
    "51.11"
  ],
  "51.14": [
    "51.12"
  ],
  "51.15": [
    "51.13"
  ],
  "51.16": [
    "51.14"
  ],
  "51.18": [
    "51.15"
  ],
  "52.4": [
    "52.1"
  ],
  "52.6": [
    "52.2"
  ],
  "52.7": [
    "52.3"
  ],
  "52.8": [
    "52.4"
  ],
  "52.10": [
    "52.5"
  ],
  "52.11": [
    "52.6"
  ],
  "52.15": [
    "52.7"
  ],
  "52.5": [
    "52.8"
  ],
  "52.12": [
    "52.9"
  ],
  "52.13": [
    "52.10"
  ],
  "52.3": [
    "52.11"
  ],
  "52.9": [
    "52.12"
  ],
  "52.17": [
    "52.13"
  ],
  "52.14": [
    "52.1"
  ],
  "53.6": [
    "53.1"
  ],
  "53.7": [
    "53.2"
  ],
  "53.8": [
    "53.3"
  ],
  "53.9": [
    "53.4"
  ],
  "53.11": [
    "53.5"
  ],
  "53.3": [
    "53.6"
  ],
  "53.12": [
    "53.7"
  ],
  "53.10": [
    "53.8"
  ],
  "53.13": [
    "53.9"
  ],
  "53.14": [
    "53.10"
  ],
  "53.16": [
    "53.11"
  ],
  "53.4": [
    "53.1"
  ],
  "53.5": [
    "53.1"
  ],
  "54.3": [
    "54.1"
  ],
  "54.4": [
    "54.2"
  ],
  "54.5": [
    "54.3"
  ],
  "54.6": [
    "54.4"
  ],
  "54.7": [
    "54.5"
  ],
  "54.8": [
    "54.6"
  ],
  "54.11": [
    "54.7"
  ],
  "54.9": [
    "54.1"
  ],
  "55.4": [
    "55.1"
  ],
  "55.6": [
    "55.2"
  ],
  "55.8": [
    "55.3"
  ],
  "55.3": [
    "55.4"
  ],
  "55.11": [
    "55.5"
  ],
  "55.12": [
    "55.6"
  ],
  "55.14": [
    "55.7"
  ],
  "55.5": [
    "55.8"
  ],
  "55.7": [
    "55.9"
  ],
  "55.13": [
    "55.10"
  ],
  "55.15": [
    "55.11"
  ],
  "55.9": [
    "55.12"
  ],
  "55.17": [
    "55.13"
  ],
  "55.10": [
    "55.1"
  ],
  "56.4": [
    "56.1"
  ],
  "56.6": [
    "56.2"
  ],
  "56.7": [
    "56.3"
  ],
  "56.10": [
    "56.4"
  ],
  "56.12": [
    "56.5"
  ],
  "56.8": [
    "56.6"
  ],
  "56.9": [
    "56.7"
  ],
  "56.14": [
    "56.8"
  ],
  "56.3": [
    "56.1"
  ],
  "56.5": [
    "56.1"
  ],
  "56.11": [
    "56.4"
  ],
  "57.4": [
    "57.1"
  ],
  "57.9": [
    "57.2"
  ],
  "57.10": [
    "57.3"
  ],
  "57.11": [
    "57.4"
  ],
  "57.6": [
    "57.5"
  ],
  "57.5": [
    "57.6"
  ],
  "57.13": [
    "57.7"
  ],
  "57.3": [
    "57.1"
  ],
  "57.7": [
    "57.6"
  ],
  "57.8": [
    "57.6"
  ],
  "58.4": [
    "58.1"
  ],
  "58.5": [
    "58.2"
  ],
  "58.6": [
    "58.3"
  ],
  "58.7": [
    "58.4"
  ],
  "58.8": [
    "58.5"
  ],
  "58.9": [
    "58.6"
  ],
  "58.10": [
    "58.7"
  ],
  "58.11": [
    "58.8"
  ],
  "58.15": [
    "58.9"
  ],
  "58.14": [
    "58.10"
  ],
  "58.17": [
    "58.11"
  ],
  "58.3": [
    "58.1"
  ],
  "58.12": [
    "58.8"
  ],
  "58.13": [
    "58.8"
  ],
  "59.5": [
    "59.1"
  ],
  "59.4": [
    "59.2"
  ],
  "59.6": [
    "59.3"
  ],
  "59.7": [
    "59.4"
  ],
  "59.9": [
    "59.5"
  ],
  "59.10": [
    "59.6"
  ],
  "59.14": [
    "59.7"
  ],
  "59.13": [
    "59.8"
  ],
  "59.11": [
    "59.9"
  ],
  "59.12": [
    "59.10"
  ],
  "59.3": [
    "59.11"
  ],
  "59.15": [
    "59.12"
  ],
  "59.16": [
    "59.13"
  ],
  "59.17": [
    "59.14"
  ],
  "59.19": [
    "59.15"
  ],
  "59.8": [
    "59.1"
  ],
  "60.3": [
    "60.1"
  ],
  "60.4": [
    "60.2"
  ],
  "60.5": [
    "60.3"
  ],
  "60.6": [
    "60.4"
  ],
  "60.8": [
    "60.5"
  ],
  "60.10": [
    "60.6"
  ],
  "60.13": [
    "60.7"
  ],
  "60.7": [
    "60.4"
  ],
  "60.9": [
    "60.6"
  ],
  "60.11": [
    "60.1"
  ],
  "61.3": [
    "61.1"
  ],
  "61.5": [
    "61.2"
  ],
  "61.6": [
    "61.3"
  ],
  "61.7": [
    "61.4"
  ],
  "61.8": [
    "61.5"
  ],
  "61.10": [
    "61.6"
  ],
  "61.12": [
    "61.7"
  ],
  "61.11": [
    "61.8"
  ],
  "61.13": [
    "61.9"
  ],
  "61.14": [
    "61.10"
  ],
  "61.16": [
    "61.11"
  ],
  "61.4": [
    "61.1"
  ],
  "61.9": [
    "61.1"
  ],
  "62.3": [
    "62.1"
  ],
  "62.5": [
    "62.2"
  ],
  "62.7": [
    "62.3"
  ],
  "62.8": [
    "62.4"
  ],
  "62.10": [
    "62.5"
  ],
  "62.9": [
    "62.6"
  ],
  "62.11": [
    "62.7"
  ],
  "62.13": [
    "62.8"
  ],
  "62.4": [
    "62.1"
  ],
  "62.6": [
    "62.3"
  ],
  "63.3": [
    "63.1"
  ],
  "63.4": [
    "63.2"
  ],
  "63.5": [
    "63.3"
  ],
  "63.8": [
    "63.4"
  ],
  "63.6": [
    "63.5"
  ],
  "63.7": [
    "63.6"
  ],
  "63.10": [
    "63.7"
  ],
  "63.13": [
    "63.8"
  ],
  "63.9": [
    "63.4"
  ],
  "63.11": [
    "63.1"
  ],
  "64.4": [
    "64.1"
  ],
  "64.5": [
    "64.2"
  ],
  "64.9": [
    "64.3"
  ],
  "64.10": [
    "64.4"
  ],
  "64.6": [
    "64.5"
  ],
  "64.7": [
    "64.6"
  ],
  "64.8": [
    "64.7"
  ],
  "64.11": [
    "64.8"
  ],
  "64.13": [
    "64.9"
  ],
  "64.3": [
    "64.1"
  ],
  "65.3": [
    "65.1"
  ],
  "65.4": [
    "65.2"
  ],
  "65.5": [
    "65.3"
  ],
  "65.7": [
    "65.4"
  ],
  "65.10": [
    "65.5"
  ],
  "65.11": [
    "65.6"
  ],
  "65.8": [
    "65.7"
  ],
  "65.9": [
    "65.8"
  ],
  "65.12": [
    "65.9"
  ],
  "65.15": [
    "65.10"
  ],
  "65.6": [
    "65.1"
  ],
  "65.13": [
    "65.1"
  ],
  "66.9": [
    "66.1"
  ],
  "66.4": [
    "66.2"
  ],
  "66.5": [
    "66.3"
  ],
  "66.6": [
    "66.4"
  ],
  "66.10": [
    "66.5"
  ],
  "66.11": [
    "66.6"
  ],
  "66.12": [
    "66.7"
  ],
  "66.15": [
    "66.8"
  ],
  "66.3": [
    "66.2"
  ],
  "66.7": [
    "66.1"
  ],
  "66.8": [
    "66.1"
  ],
  "66.13": [
    "66.2"
  ],
  "67.3": [
    "67.1"
  ],
  "67.6": [
    "67.2"
  ],
  "67.7": [
    "67.3"
  ],
  "67.8": [
    "67.4"
  ],
  "67.11": [
    "67.5"
  ],
  "67.4": [
    "67.6"
  ],
  "67.5": [
    "67.7"
  ],
  "67.9": [
    "67.8"
  ],
  "67.13": [
    "67.9"
  ],
  "67.15": [
    "67.10"
  ],
  "67.10": [
    "67.8"
  ],
  "67.12": [
    "67.1"
  ],
  "68.4": [
    "68.1"
  ],
  "68.5": [
    "68.2"
  ],
  "68.6": [
    "68.3"
  ],
  "68.8": [
    "68.4"
  ],
  "68.10": [
    "68.5"
  ],
  "68.12": [
    "68.6"
  ],
  "68.13": [
    "68.7"
  ],
  "68.14": [
    "68.8"
  ],
  "68.7": [
    "68.9"
  ],
  "68.16": [
    "68.10"
  ],
  "68.3": [
    "68.1"
  ],
  "68.9": [
    "68.9"
  ],
  "68.11": [
    "68.1"
  ],
  "69.3": [
    "69.1"
  ],
  "69.4": [
    "69.2"
  ],
  "69.5": [
    "69.3"
  ],
  "69.6": [
    "69.4"
  ],
  "69.7": [
    "69.5"
  ],
  "69.11": [
    "69.6"
  ],
  "69.12": [
    "69.7"
  ],
  "69.14": [
    "69.8"
  ],
  "69.9": [
    "69.9"
  ],
  "69.10": [
    "69.10"
  ],
  "69.8": [
    "69.11"
  ],
  "69.13": [
    "69.12"
  ],
  "69.15": [
    "69.13"
  ],
  "69.17": [
    "69.14"
  ],
  "70.3": [
    "70.1"
  ],
  "70.7": [
    "70.2"
  ],
  "70.9": [
    "70.3"
  ],
  "70.8": [
    "70.4"
  ],
  "70.5": [
    "70.5"
  ],
  "70.6": [
    "70.6"
  ],
  "70.10": [
    "70.7"
  ],
  "70.12": [
    "70.8"
  ],
  "70.4": [
    "70.1"
  ],
  "71.3": [
    "71.1"
  ],
  "71.5": [
    "71.2"
  ],
  "71.6": [
    "71.3"
  ],
  "71.7": [
    "71.4"
  ],
  "71.8": [
    "71.5"
  ],
  "71.4": [
    "71.6"
  ],
  "71.11": [
    "71.7"
  ],
  "71.9": [
    "71.1"
  ],
  "72.3": [
    "72.1"
  ],
  "72.5": [
    "72.2"
  ],
  "72.6": [
    "72.3"
  ],
  "72.7": [
    "72.4"
  ],
  "72.10": [
    "72.5"
  ],
  "72.4": [
    "72.6"
  ],
  "72.12": [
    "72.7"
  ],
  "72.11": [
    "72.8"
  ],
  "72.13": [
    "72.9"
  ],
  "72.14": [
    "72.10"
  ],
  "72.17": [
    "72.11"
  ],
  "72.8": [
    "72.1"
  ],
  "72.9": [
    "72.5"
  ],
  "72.15": [
    "72.11"
  ],
  "73.5": [
    "73.1"
  ],
  "73.6": [
    "73.2"
  ],
  "73.8": [
    "73.3"
  ],
  "73.9": [
    "73.4"
  ],
  "73.3": [
    "73.5"
  ],
  "73.7": [
    "73.6"
  ],
  "73.11": [
    "73.7"
  ],
  "73.13": [
    "73.8"
  ],
  "73.4": [
    "73.1"
  ],
  "73.10": [
    "73.7"
  ],
  "74.4": [
    "74.1"
  ],
  "74.5": [
    "74.2"
  ],
  "74.3": [
    "74.3"
  ],
  "74.8": [
    "74.4"
  ],
  "74.9": [
    "74.5"
  ],
  "74.7": [
    "74.6"
  ],
  "74.10": [
    "74.7"
  ],
  "74.11": [
    "74.8"
  ],
  "74.12": [
    "74.9"
  ],
  "74.14": [
    "74.10"
  ],
  "74.6": [
    "74.1"
  ],
  "75.3": [
    "75.1"
  ],
  "75.4": [
    "75.2"
  ],
  "75.5": [
    "75.3"
  ],
  "75.6": [
    "75.4"
  ],
  "75.9": [
    "75.5"
  ],
  "75.12": [
    "75.6"
  ],
  "75.13": [
    "75.7"
  ],
  "75.8": [
    "75.8"
  ],
  "75.10": [
    "75.9"
  ],
  "75.15": [
    "75.10"
  ],
  "75.7": [
    "75.1"
  ],
  "75.11": [
    "75.6"
  ],
  "76.3": [
    "76.1"
  ],
  "76.5": [
    "76.2"
  ],
  "76.6": [
    "76.3"
  ],
  "76.10": [
    "76.4"
  ],
  "76.11": [
    "76.5"
  ],
  "76.12": [
    "76.6"
  ],
  "76.7": [
    "76.7"
  ],
  "76.4": [
    "76.8"
  ],
  "76.8": [
    "76.9"
  ],
  "76.14": [
    "76.10"
  ],
  "76.9": [
    "76.1"
  ],
  "77.4": [
    "77.1"
  ],
  "77.5": [
    "77.2"
  ],
  "77.6": [
    "77.3"
  ],
  "77.3": [
    "77.4"
  ],
  "77.10": [
    "77.5"
  ],
  "77.14": [
    "77.6"
  ],
  "77.7": [
    "77.7"
  ],
  "77.9": [
    "77.8"
  ],
  "77.8": [
    "77.9"
  ],
  "77.16": [
    "77.10"
  ],
  "77.11": [
    "77.1"
  ],
  "77.12": [
    "77.1"
  ],
  "77.13": [
    "77.1"
  ],
  "78.3": [
    "78.1"
  ],
  "78.11": [
    "78.2"
  ],
  "78.6": [
    "78.3"
  ],
  "78.8": [
    "78.4"
  ],
  "78.5": [
    "78.5"
  ],
  "78.14": [
    "78.6"
  ],
  "78.7": [
    "78.7"
  ],
  "78.10": [
    "78.8"
  ],
  "78.12": [
    "78.9"
  ],
  "78.13": [
    "78.10"
  ],
  "78.9": [
    "78.11"
  ],
  "78.15": [
    "78.12"
  ],
  "78.18": [
    "78.13"
  ],
  "78.4": [
    "78.1"
  ],
  "78.16": [
    "78.12"
  ],
  "79.6": [
    "79.1"
  ],
  "79.7": [
    "79.2"
  ],
  "79.9": [
    "79.3"
  ],
  "79.10": [
    "79.4"
  ],
  "79.11": [
    "79.5"
  ],
  "79.5": [
    "79.6"
  ],
  "79.12": [
    "79.7"
  ],
  "79.13": [
    "79.8"
  ],
  "79.8": [
    "79.9"
  ],
  "79.3": [
    "79.10"
  ],
  "79.15": [
    "79.11"
  ],
  "79.17": [
    "79.12"
  ],
  "79.4": [
    "79.6"
  ],
  "79.14": [
    "79.1"
  ],
  "80.4": [
    "80.1"
  ],
  "80.5": [
    "80.2"
  ],
  "80.6": [
    "80.3"
  ],
  "80.9": [
    "80.4"
  ],
  "80.13": [
    "80.5"
  ],
  "80.8": [
    "80.6"
  ],
  "80.7": [
    "80.7"
  ],
  "80.10": [
    "80.8"
  ],
  "80.14": [
    "80.9"
  ],
  "80.15": [
    "80.10"
  ],
  "80.17": [
    "80.11"
  ],
  "80.3": [
    "80.1"
  ],
  "80.11": [
    "80.8"
  ],
  "80.12": [
    "80.8"
  ],
  "81.3": [
    "81.1"
  ],
  "81.5": [
    "81.2"
  ],
  "81.6": [
    "81.3"
  ],
  "81.7": [
    "81.4"
  ],
  "81.8": [
    "81.5"
  ],
  "81.11": [
    "81.6"
  ],
  "81.9": [
    "81.7"
  ],
  "81.10": [
    "81.8"
  ],
  "81.14": [
    "81.9"
  ],
  "81.4": [
    "81.1"
  ],
  "81.12": [
    "81.1"
  ],
  "82.3": [
    "82.1"
  ],
  "82.4": [
    "82.2"
  ],
  "82.5": [
    "82.3"
  ],
  "82.6": [
    "82.4"
  ],
  "82.7": [
    "82.5"
  ],
  "82.8": [
    "82.6"
  ],
  "82.11": [
    "82.7"
  ],
  "82.9": [
    "82.1"
  ],
  "83.4": [
    "83.1"
  ],
  "83.5": [
    "83.2"
  ],
  "83.6": [
    "83.3"
  ],
  "83.7": [
    "83.4"
  ],
  "83.3": [
    "83.5"
  ],
  "83.8": [
    "83.6"
  ],
  "83.9": [
    "83.7"
  ],
  "83.10": [
    "83.8"
  ],
  "83.11": [
    "83.9"
  ],
  "83.15": [
    "83.10"
  ],
  "83.12": [
    "83.5"
  ],
  "83.13": [
    "83.1"
  ],
  "84.4": [
    "84.1"
  ],
  "84.5": [
    "84.2"
  ],
  "84.6": [
    "84.3"
  ],
  "84.8": [
    "84.4"
  ],
  "84.7": [
    "84.5"
  ],
  "84.10": [
    "84.6"
  ],
  "84.3": [
    "84.7"
  ],
  "84.9": [
    "84.8"
  ],
  "84.12": [
    "84.9"
  ],
  "84.11": [
    "84.10"
  ],
  "84.15": [
    "84.11"
  ],
  "84.13": [
    "84.1"
  ],
  "85.4": [
    "85.1"
  ],
  "85.5": [
    "85.2"
  ],
  "85.6": [
    "85.3"
  ],
  "85.7": [
    "85.4"
  ],
  "85.8": [
    "85.5"
  ],
  "85.9": [
    "85.6"
  ],
  "85.10": [
    "85.7"
  ],
  "85.12": [
    "85.8"
  ],
  "85.14": [
    "85.9"
  ],
  "85.3": [
    "85.1"
  ],
  "85.11": [
    "85.8"
  ],
  "86.4": [
    "86.1"
  ],
  "86.5": [
    "86.2"
  ],
  "86.6": [
    "86.3"
  ],
  "86.8": [
    "86.4"
  ],
  "86.9": [
    "86.5"
  ],
  "86.7": [
    "86.6"
  ],
  "86.11": [
    "86.7"
  ],
  "86.3": [
    "86.1"
  ],
  "87.3": [
    "87.1"
  ],
  "87.4": [
    "87.2"
  ],
  "87.5": [
    "87.3"
  ],
  "87.6": [
    "87.4"
  ],
  "87.8": [
    "87.5"
  ],
  "87.11": [
    "87.6"
  ],
  "87.7": [
    "87.7"
  ],
  "87.9": [
    "87.8"
  ],
  "87.10": [
    "87.9"
  ],
  "87.13": [
    "87.10"
  ],
  "88.3": [
    "88.1"
  ],
  "88.4": [
    "88.2"
  ],
  "88.6": [
    "88.3"
  ],
  "88.7": [
    "88.4"
  ],
  "88.8": [
    "88.5"
  ],
  "88.5": [
    "88.6"
  ],
  "88.9": [
    "88.7"
  ],
  "88.11": [
    "88.8"
  ],
  "88.12": [
    "88.9"
  ],
  "88.13": [
    "88.10"
  ],
  "88.14": [
    "88.11"
  ],
  "88.16": [
    "88.12"
  ],
  "88.20": [
    "88.13"
  ],
  "88.10": [
    "88.1"
  ],
  "88.15": [
    "88.12"
  ],
  "88.17": [
    "88.1"
  ],
  "88.18": [
    "88.1"
  ],
  "89.4": [
    "89.1"
  ],
  "89.6": [
    "89.2"
  ],
  "89.7": [
    "89.3"
  ],
  "89.12": [
    "89.4"
  ],
  "89.3": [
    "89.5"
  ],
  "89.8": [
    "89.6"
  ],
  "89.9": [
    "89.7"
  ],
  "89.10": [
    "89.8"
  ],
  "89.11": [
    "89.9"
  ],
  "89.16": [
    "89.10"
  ],
  "89.5": [
    "89.2"
  ],
  "89.13": [
    "89.1"
  ],
  "89.14": [
    "89.1"
  ],
  "90.3": [
    "90.1"
  ],
  "90.4": [
    "90.2"
  ],
  "90.5": [
    "90.3"
  ],
  "90.8": [
    "90.4"
  ],
  "90.9": [
    "90.5"
  ],
  "90.7": [
    "90.6"
  ],
  "90.6": [
    "90.5"
  ],
  "90.10": [
    "90.1"
  ],
  "90.12": [
    "90.1"
  ],
  "91.3": [
    "91.1"
  ],
  "91.5": [
    "91.2"
  ],
  "91.6": [
    "91.3"
  ],
  "91.7": [
    "91.4"
  ],
  "91.10": [
    "91.5"
  ],
  "91.12": [
    "91.6"
  ],
  "91.8": [
    "91.7"
  ],
  "91.9": [
    "91.8"
  ],
  "91.11": [
    "91.9"
  ],
  "91.14": [
    "91.10"
  ],
  "91.4": [
    "91.1"
  ],
  "92.4": [
    "92.1"
  ],
  "92.6": [
    "92.2"
  ],
  "92.8": [
    "92.3"
  ],
  "92.9": [
    "92.4"
  ],
  "92.11": [
    "92.5"
  ],
  "92.3": [
    "92.6"
  ],
  "92.7": [
    "92.7"
  ],
  "92.10": [
    "92.8"
  ],
  "92.14": [
    "92.9"
  ],
  "92.5": [
    "92.1"
  ],
  "92.12": [
    "92.1"
  ],
  "93.4": [
    "93.1"
  ],
  "93.5": [
    "93.2"
  ],
  "93.6": [
    "93.3"
  ],
  "93.9": [
    "93.4"
  ],
  "93.11": [
    "93.5"
  ],
  "93.8": [
    "93.6"
  ],
  "93.10": [
    "93.7"
  ],
  "93.7": [
    "93.8"
  ],
  "93.13": [
    "93.9"
  ],
  "93.3": [
    "93.1"
  ],
  "94.3": [
    "94.1"
  ],
  "94.7": [
    "94.2"
  ],
  "94.4": [
    "94.3"
  ],
  "94.5": [
    "94.4"
  ],
  "94.6": [
    "94.5"
  ],
  "94.8": [
    "94.6"
  ],
  "94.9": [
    "94.7"
  ],
  "94.10": [
    "94.8"
  ],
  "94.11": [
    "94.9"
  ],
  "94.14": [
    "94.10"
  ],
  "94.12": [
    "94.1"
  ],
  "95.3": [
    "95.1"
  ],
  "95.5": [
    "95.2"
  ],
  "95.8": [
    "95.3"
  ],
  "95.9": [
    "95.4"
  ],
  "95.12": [
    "95.5"
  ],
  "95.7": [
    "95.6"
  ],
  "95.11": [
    "95.7"
  ],
  "95.14": [
    "95.8"
  ],
  "95.4": [
    "95.1"
  ],
  "95.6": [
    "95.1"
  ],
  "95.10": [
    "95.1"
  ],
  "96.4": [
    "96.1"
  ],
  "96.5": [
    "96.2"
  ],
  "96.6": [
    "96.3"
  ],
  "96.7": [
    "96.4"
  ],
  "96.8": [
    "96.5"
  ],
  "96.9": [
    "96.6"
  ],
  "96.11": [
    "96.7"
  ],
  "96.12": [
    "96.8"
  ],
  "96.13": [
    "96.9"
  ],
  "96.14": [
    "96.10"
  ],
  "96.3": [
    "96.1"
  ],
  "96.10": [
    "96.1"
  ],
  "97.4": [
    "97.1"
  ],
  "97.5": [
    "97.2"
  ],
  "97.11": [
    "97.3"
  ],
  "97.12": [
    "97.4"
  ],
  "97.13": [
    "97.5"
  ],
  "97.3": [
    "97.6"
  ],
  "97.6": [
    "97.7"
  ],
  "97.7": [
    "97.8"
  ],
  "97.8": [
    "97.9"
  ],
  "97.9": [
    "97.10"
  ],
  "97.10": [
    "97.11"
  ],
  "97.14": [
    "97.1"
  ],
  "98.4": [
    "98.1"
  ],
  "98.5": [
    "98.2"
  ],
  "98.6": [
    "98.3"
  ],
  "98.7": [
    "98.4"
  ],
  "98.3": [
    "98.5"
  ],
  "98.8": [
    "98.6"
  ],
  "98.9": [
    "98.7"
  ],
  "98.11": [
    "98.8"
  ],
  "98.10": [
    "98.9"
  ],
  "98.12": [
    "98.10"
  ],
  "98.13": [
    "98.1"
  ],
  "98.14": [
    "98.1"
  ],
  "99.4": [
    "99.1"
  ],
  "99.5": [
    "99.2"
  ],
  "99.7": [
    "99.3"
  ],
  "99.9": [
    "99.4"
  ],
  "99.3": [
    "99.5"
  ],
  "99.12": [
    "99.6"
  ],
  "99.8": [
    "99.7"
  ],
  "99.6": [
    "99.1"
  ],
  "99.10": [
    "99.1"
  ],
  "99.11": [
    "99.1"
  ],
  "99.13": [
    "99.1"
  ],
  "100.3": [
    "100.1"
  ],
  "100.5": [
    "100.2"
  ],
  "100.12": [
    "100.3"
  ],
  "100.14": [
    "100.4"
  ],
  "100.10": [
    "100.5"
  ],
  "100.16": [
    "100.6"
  ],
  "100.17": [
    "100.7"
  ],
  "100.13": [
    "100.8"
  ],
  "100.8": [
    "100.9"
  ],
  "100.15": [
    "100.10"
  ],
  "100.4": [
    "100.1"
  ],
  "100.6": [
    "100.1"
  ],
  "100.7": [
    "100.1"
  ],
  "100.9": [
    "100.1"
  ],
  "100.11": [
    "100.1"
  ],
  "101.4": [
    "101.1"
  ],
  "101.7": [
    "101.2"
  ],
  "101.10": [
    "101.3"
  ],
  "101.11": [
    "101.4"
  ],
  "101.9": [
    "101.5"
  ],
  "101.12": [
    "101.6"
  ],
  "101.6": [
    "101.7"
  ],
  "101.3": [
    "101.8"
  ],
  "101.5": [
    "101.1"
  ],
  "101.8": [
    "101.1"
  ],
  "101.13": [
    "101.8"
  ],
  "102.3": [
    "102.1"
  ],
  "102.5": [
    "102.2"
  ],
  "102.6": [
    "102.3"
  ],
  "102.8": [
    "102.4"
  ],
  "102.11": [
    "102.5"
  ],
  "102.9": [
    "102.6"
  ],
  "102.10": [
    "102.7"
  ],
  "102.4": [
    "102.1"
  ],
  "102.7": [
    "102.1"
  ],
  "103.3": [
    "103.1"
  ],
  "103.4": [
    "103.2"
  ],
  "103.5": [
    "103.3"
  ],
  "103.6": [
    "103.4"
  ],
  "103.7": [
    "103.5"
  ],
  "103.8": [
    "103.6"
  ],
  "103.13": [
    "103.7"
  ],
  "103.10": [
    "103.8"
  ],
  "103.11": [
    "103.9"
  ],
  "103.12": [
    "103.10"
  ],
  "103.15": [
    "103.11"
  ],
  "103.9": [
    "103.6"
  ],
  "103.14": [
    "103.1"
  ],
  "103.16": [
    "103.1"
  ],
  "104.3": [
    "104.1"
  ],
  "104.5": [
    "104.2"
  ],
  "104.6": [
    "104.3"
  ],
  "104.7": [
    "104.4"
  ],
  "104.8": [
    "104.5"
  ],
  "104.11": [
    "104.6"
  ],
  "104.9": [
    "104.7"
  ],
  "104.10": [
    "104.8"
  ],
  "104.12": [
    "104.9"
  ],
  "104.4": [
    "104.1"
  ],
  "104.13": [
    "104.1"
  ],
  "105.5": [
    "105.1"
  ],
  "105.6": [
    "105.2"
  ],
  "105.7": [
    "105.3"
  ],
  "105.8": [
    "105.4"
  ],
  "105.9": [
    "105.5"
  ],
  "105.4": [
    "105.6"
  ],
  "105.3": [
    "105.7"
  ],
  "105.10": [
    "105.8"
  ],
  "105.2": [
    "105.8"
  ],
  "105.11": [
    "105.8"
  ],
  "105.12": [
    "105.1"
  ],
  "105.13": [
    "105.8"
  ],
  "105.14": [
    "105.8"
  ]
};
